var jsx = [{
  "type": 1,
  "degree": 1,
  "title": "组成合金的最基本的独立物质称为（ ）。",
  "ans": "B",
  "opts": [{
    "title": "相",
    "value": "A",
    "checked": 0
  }, {
    "title": "组元",
    "value": "B",
    "checked": 0
  }, {
    "title": "组织",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "08F钢的平均含碳量为（ ）%。",
  "ans": "A",
  "opts": [{
    "title": "0.08",
    "value": "A",
    "checked": 0
  }, {
    "title": "0.8",
    "value": "B",
    "checked": 0
  }, {
    "title": "8",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "下列牌号中，属于工具钢的有（ ）。",
  "ans": "C",
  "opts": [{
    "title": "20",
    "value": "A",
    "checked": 0
  }, {
    "title": "65Mn",
    "value": "B",
    "checked": 0
  }, {
    "title": "T10A",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "下列牌号中，最适合制造车床主轴的是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "T8",
    "value": "A",
    "checked": 0
  }, {
    "title": "Q195",
    "value": "B",
    "checked": 0
  }, {
    "title": "45",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "合金发生固溶强化的主要原因是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "晶格类型发生变化",
    "value": "A",
    "checked": 0
  }, {
    "title": "晶粒细化",
    "value": "B",
    "checked": 0
  }, {
    "title": "晶格发生畸变",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "铁碳合金相图上的共析线是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "ACD",
    "value": "A",
    "checked": 0
  }, {
    "title": "ECF",
    "value": "B",
    "checked": 0
  }, {
    "title": "PSK",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "下列钢号中，属于工具钢的是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "T10",
    "value": "A",
    "checked": 0
  }, {
    "title": "08F",
    "value": "B",
    "checked": 0
  }, {
    "title": "45",
    "value": "C",
    "checked": 0
  }, {
    "title": "65",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "C%靠近（ ）的铁碳合金具有良好的铸造性能。",
  "ans": "C",
  "opts": [{
    "title": "0.77",
    "value": "A",
    "checked": 0
  }, {
    "title": "2.11",
    "value": "B",
    "checked": 0
  }, {
    "title": "4.3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "下列铸钢牌号中，（ ）可以做轧机机架。",
  "ans": "C",
  "opts": [{
    "title": "ZG200-400",
    "value": "A",
    "checked": 0
  }, {
    "title": "ZG350-450",
    "value": "B",
    "checked": 0
  }, {
    "title": "ZG270-500",
    "value": "C",
    "checked": 0
  }, {
    "title": "ZG310-570",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "金属结晶过程形成的晶核主要按（ ）生长方式长大。",
  "ans": "B",
  "opts": [{
    "title": "胞状",
    "value": "A",
    "checked": 0
  }, {
    "title": "树枝状",
    "value": "B",
    "checked": 0
  }, {
    "title": "平面状",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "位错的特点之一是在外力下很容易在晶体中（ ）。",
  "ans": "A",
  "opts": [{
    "title": "移动",
    "value": "A",
    "checked": 0
  }, {
    "title": "错动",
    "value": "B",
    "checked": 0
  }, {
    "title": "不动",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "晶体与非晶体相比具有（ ）。",
  "ans": "B",
  "opts": [{
    "title": "不相同性",
    "value": "A",
    "checked": 0
  }, {
    "title": "各向同向性",
    "value": "B",
    "checked": 0
  }, {
    "title": "各向异向性",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "通过原子中心的直线，可代表晶格空间的一定方向，称为（ ）。",
  "ans": "B",
  "opts": [{
    "title": "方向",
    "value": "A",
    "checked": 0
  }, {
    "title": "位向",
    "value": "B",
    "checked": 0
  }, {
    "title": "位置",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "镁（Mg），铍（Pe），镉（Cd)及锌(Zn)等金属具有（ ）晶体结构。",
  "ans": "C",
  "opts": [{
    "title": "体心立方",
    "value": "A",
    "checked": 0
  }, {
    "title": "面心立方",
    "value": "B",
    "checked": 0
  }, {
    "title": "密排六方",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "一般来说，（ ）具有较高的强度和韧度。",
  "ans": "A",
  "opts": [{
    "title": "细晶粒金属",
    "value": "A",
    "checked": 0
  }, {
    "title": "粗晶粒金属",
    "value": "B",
    "checked": 0
  }, {
    "title": "中等晶粒金属",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "增加过冷度细化晶粒，这种方法一般只适用（ ）。",
  "ans": "A",
  "opts": [{
    "title": "中，小铸件",
    "value": "A",
    "checked": 0
  }, {
    "title": "大，中铸件",
    "value": "B",
    "checked": 0
  }, {
    "title": "大型铸件",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "一种固定成分均匀一致的固相，（ ）在恒温时同时析出两种化学成分和晶体结构皆不同",
  "ans": "B",
  "opts": [{
    "title": "包晶反应",
    "value": "A",
    "checked": 0
  }, {
    "title": "共析反应",
    "value": "B",
    "checked": 0
  }, {
    "title": "共晶反应",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "奥氏体与渗碳体的共晶混合物，称为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "莱氏体",
    "value": "A",
    "checked": 0
  }, {
    "title": "珠光体",
    "value": "B",
    "checked": 0
  }, {
    "title": "贝氏体",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "镇静钢的脱氧程度（ ）。",
  "ans": "B",
  "opts": [{
    "title": "不完全",
    "value": "A",
    "checked": 0
  }, {
    "title": "完全",
    "value": "B",
    "checked": 0
  }, {
    "title": "介于两者之间",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "从奥氏体中析出的渗碳体为（ ）。",
  "ans": "B",
  "opts": [{
    "title": "一次渗碳体",
    "value": "A",
    "checked": 0
  }, {
    "title": "二次渗碳体",
    "value": "B",
    "checked": 0
  }, {
    "title": "三次渗碳体",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "在铁碳相图中，随着温度的下降，碳在奥氏体的溶解度是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "增加",
    "value": "A",
    "checked": 0
  }, {
    "title": "减少",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "表示原子在晶体中排列规律的空间格架，叫做（ ）。",
  "ans": "A",
  "opts": [{
    "title": "晶胞",
    "value": "A",
    "checked": 0
  }, {
    "title": "晶格",
    "value": "B",
    "checked": 0
  }, {
    "title": "晶格常数",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "能够完整地反映晶格特征的最小几何单元成为（ ）。",
  "ans": "B",
  "opts": [{
    "title": "晶胞",
    "value": "A",
    "checked": 0
  }, {
    "title": "晶格",
    "value": "B",
    "checked": 0
  }, {
    "title": "晶格常数",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "α—Fe是具有（ ）晶格的铁。",
  "ans": "A",
  "opts": [{
    "title": "体心立方",
    "value": "A",
    "checked": 0
  }, {
    "title": "面心立方",
    "value": "B",
    "checked": 0
  }, {
    "title": "密排六方",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "γ-Fe是具有（ ）晶格的铁。",
  "ans": "B",
  "opts": [{
    "title": "体心立方",
    "value": "A",
    "checked": 0
  }, {
    "title": "面心立方",
    "value": "B",
    "checked": 0
  }, {
    "title": "密排六方",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "晶格中有空位、间隙原子和置代原子的存在，会引起（ ）。",
  "ans": "C",
  "opts": [{
    "title": "加工硬化",
    "value": "A",
    "checked": 0
  }, {
    "title": "弹性变形",
    "value": "B",
    "checked": 0
  }, {
    "title": "晶格畸变",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "含碳量为1.2%的铁碳合金，在室温下的组织为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "珠光体",
    "value": "A",
    "checked": 0
  }, {
    "title": "珠光体加铁素体",
    "value": "B",
    "checked": 0
  }, {
    "title": "珠光体加二次渗碳体",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "铁碳合金相图上的ES线，其代号用（ ）表示。",
  "ans": "C",
  "opts": [{
    "title": "A1",
    "value": "A",
    "checked": 0
  }, {
    "title": "A3",
    "value": "B",
    "checked": 0
  }, {
    "title": "Acm",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "PSK线用代号（ ）表示。",
  "ans": "A",
  "opts": [{
    "title": "A1",
    "value": "A",
    "checked": 0
  }, {
    "title": "A3",
    "value": "B",
    "checked": 0
  }, {
    "title": "Acm",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "GS线用代号（ ）表示。",
  "ans": "B",
  "opts": [{
    "title": "A1",
    "value": "A",
    "checked": 0
  }, {
    "title": "A3",
    "value": "B",
    "checked": 0
  }, {
    "title": "Acm",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "从液体中结晶出的渗碳体为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "一次渗碳体",
    "value": "A",
    "checked": 0
  }, {
    "title": "二次渗碳体",
    "value": "B",
    "checked": 0
  }, {
    "title": "三次渗碳体",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "将含碳量为1.5%的铁碳合金加热到650℃时，其组织为（ ）。，",
  "ans": "C",
  "opts": [{
    "title": "珠光体",
    "value": "A",
    "checked": 0
  }, {
    "title": "奥氏体",
    "value": "B",
    "checked": 0
  }, {
    "title": "珠光体加渗碳体",
    "value": "C",
    "checked": 0
  }, {
    "title": "奥氏体加渗碳体",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "将含碳量为1.5%的铁碳合金加热到850℃时,其组织为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "珠光体",
    "value": "A",
    "checked": 0
  }, {
    "title": "奥氏体",
    "value": "B",
    "checked": 0
  }, {
    "title": "珠光体加渗碳体",
    "value": "C",
    "checked": 0
  }, {
    "title": "奥氏体加渗碳体",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "将含碳量为1.5%的铁碳合金加热到1100℃时其组织为（ ）。",
  "ans": "B",
  "opts": [{
    "title": "珠光体",
    "value": "A",
    "checked": 0
  }, {
    "title": "奥氏体",
    "value": "B",
    "checked": 0
  }, {
    "title": "珠光体加渗碳体",
    "value": "C",
    "checked": 0
  }, {
    "title": "奥氏体加渗碳体",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "亚共析钢冷却到GS线时，要从奥氏体中析出（ ）。",
  "ans": "B",
  "opts": [{
    "title": "珠光体",
    "value": "A",
    "checked": 0
  }, {
    "title": "铁素体",
    "value": "B",
    "checked": 0
  }, {
    "title": "渗碳体",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "亚共析钢冷却到PSK线时，要发生共析转变，奥氏体转变成（ ）。",
  "ans": "A",
  "opts": [{
    "title": "珠光体",
    "value": "A",
    "checked": 0
  }, {
    "title": "铁素体",
    "value": "B",
    "checked": 0
  }, {
    "title": "珠光体加铁素体",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "铁碳合金相图上的液相线是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "ECF",
    "value": "A",
    "checked": 0
  }, {
    "title": "AECF",
    "value": "B",
    "checked": 0
  }, {
    "title": "ACD",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "铁碳合金相图上的固相线是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "ECF",
    "value": "A",
    "checked": 0
  }, {
    "title": "AECF",
    "value": "B",
    "checked": 0
  }, {
    "title": "ACD",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "渗碳体的含碳量为（ ）%。",
  "ans": "C",
  "opts": [{
    "title": "0.77",
    "value": "A",
    "checked": 0
  }, {
    "title": "2.11",
    "value": "B",
    "checked": 0
  }, {
    "title": "6.69",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "铁碳合金共晶转变的温度是（ ）℃。",
  "ans": "B",
  "opts": [{
    "title": "727",
    "value": "A",
    "checked": 0
  }, {
    "title": "1148",
    "value": "B",
    "checked": 0
  }, {
    "title": "1227",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "铁碳合金共析转变的温度是（ ）℃。",
  "ans": "A",
  "opts": [{
    "title": "727",
    "value": "A",
    "checked": 0
  }, {
    "title": "1148",
    "value": "B",
    "checked": 0
  }, {
    "title": "1227",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "钢与铁的含碳量的分界点是（ ）%。",
  "ans": "B",
  "opts": [{
    "title": "0.77",
    "value": "A",
    "checked": 0
  }, {
    "title": "2.11",
    "value": "B",
    "checked": 0
  }, {
    "title": "6.69",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "珠光体的平均含碳量为（ ）%。",
  "ans": "A",
  "opts": [{
    "title": "0.77",
    "value": "A",
    "checked": 0
  }, {
    "title": "2.11",
    "value": "B",
    "checked": 0
  }, {
    "title": "6.69",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "T8钢中的平均含碳量为（ ）。",
  "ans": "B",
  "opts": [{
    "title": "0.0008",
    "value": "A",
    "checked": 0
  }, {
    "title": "0.008",
    "value": "B",
    "checked": 0
  }, {
    "title": "0.08",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "普通、优质和高级优质钢是按钢的（ ）进行划分的。",
  "ans": "A",
  "opts": [{
    "title": "力学性能的高低",
    "value": "A",
    "checked": 0
  }, {
    "title": "S，P含量的多少",
    "value": "B",
    "checked": 0
  }, {
    "title": "Mn，Si含量的多少",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "在下列牌号中属于优质碳素结构钢的有（ ）。",
  "ans": "B",
  "opts": [{
    "title": "T8A",
    "value": "A",
    "checked": 0
  }, {
    "title": "08F",
    "value": "B",
    "checked": 0
  }, {
    "title": "Q235—A·F",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "在下列牌号中属于工具钢的有（ ）。",
  "ans": "C",
  "opts": [{
    "title": "20",
    "value": "A",
    "checked": 0
  }, {
    "title": "65Mn",
    "value": "B",
    "checked": 0
  }, {
    "title": "T10A",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "冷冲压件的材料为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "08F",
    "value": "A",
    "checked": 0
  }, {
    "title": "45",
    "value": "B",
    "checked": 0
  }, {
    "title": "65Mn",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "齿轮的材料为（ ）。",
  "ans": "B",
  "opts": [{
    "title": "08F",
    "value": "A",
    "checked": 0
  }, {
    "title": "45",
    "value": "B",
    "checked": 0
  }, {
    "title": "65Mn",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "小弹簧的材料为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "08F",
    "value": "A",
    "checked": 0
  }, {
    "title": "45",
    "value": "B",
    "checked": 0
  }, {
    "title": "65Mn",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "锉刀的选材为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "T8",
    "value": "A",
    "checked": 0
  }, {
    "title": "T10",
    "value": "B",
    "checked": 0
  }, {
    "title": "T12",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高级优质钢的S、P含量为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "S≤0.050%P≤0.045%",
    "value": "A",
    "checked": 0
  }, {
    "title": "S≤0.035%P≤0.035%",
    "value": "B",
    "checked": 0
  }, {
    "title": "S≤0.025%P≤0.025%",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "通常使用的螺钉的材料含碳量为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "08—25%",
    "value": "A",
    "checked": 0
  }, {
    "title": "30—55%",
    "value": "B",
    "checked": 0
  }, {
    "title": "60%以上",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "石墨呈片状或曲片状存在的铸铁是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "可锻铸铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "灰铸铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "球墨铸铁",
    "value": "C",
    "checked": 0
  }, {
    "title": "蠕墨铸铁",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "石墨呈紧密团絮状存在的铸铁是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "可锻铸铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "灰铸铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "球墨铸铁",
    "value": "C",
    "checked": 0
  }, {
    "title": "蠕墨铸铁",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "石墨呈球状状存在的铸铁是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "可锻铸铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "灰铸铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "球墨铸铁",
    "value": "C",
    "checked": 0
  }, {
    "title": "蠕墨铸铁",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "石墨呈蠕虫状存在的铸铁是（ ）。",
  "ans": "D",
  "opts": [{
    "title": "可锻铸铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "灰铸铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "球墨铸铁",
    "value": "C",
    "checked": 0
  }, {
    "title": "蠕墨铸铁",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "铸件厚会（ ）石墨化。",
  "ans": "A",
  "opts": [{
    "title": "促进",
    "value": "A",
    "checked": 0
  }, {
    "title": "阻碍",
    "value": "B",
    "checked": 0
  }, {
    "title": "不影响",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "孕育处理适用于（ ）。",
  "ans": "A",
  "opts": [{
    "title": "灰铸铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "可锻铸铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "球墨铸铁",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "球磨铸铁的石墨割裂基体的作用（ ）。",
  "ans": "B",
  "opts": [{
    "title": "大",
    "value": "A",
    "checked": 0
  }, {
    "title": "小",
    "value": "B",
    "checked": 0
  }, {
    "title": "没有",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "蠕墨铸铁适合制造强度较高或承受（ ）载荷及热疲劳的零件。",
  "ans": "C",
  "opts": [{
    "title": "静",
    "value": "A",
    "checked": 0
  }, {
    "title": "交变",
    "value": "B",
    "checked": 0
  }, {
    "title": "冲击",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "QT700-2是指（ ）的牌号。",
  "ans": "C",
  "opts": [{
    "title": "灰铸铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "可锻铸铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "球墨铸铁",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "γ-Fe与α-Fe均属纯铁，因此其性能毫无差异。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "金属的同素异构转变是在恒温下进行的。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "同素异构转变也遵循晶核形成与晶核长大的规律。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "多晶体的塑性变形受晶界的影响，晶界越多，变形越容易。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "固溶体的晶格类型与其溶剂的晶格类型相同。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "碳在γ-Fe中的溶解度比在α-Fe中的溶解度低。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "Q215钢适用于制造桥梁，船舶等。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "奥氏体向铁素体的转变是铁发生同素异构转变的结果。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "同素异构转变是热处理的前提条件。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "金属化合物晶格类型完全不同于任一组元的晶格类型。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "碳在奥氏体中的溶解度随温度的提高而减小。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "金属的同素异构转变又称为重结晶。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "一般情况下，金属的晶粒越细，其力学性能越差。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "同一晶格的不同晶面和晶向上原子排列的疏密程度相同，因此原子结合力也相同。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "空位和间隙原子属于线缺陷。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "晶体缺陷的存在一定使材料的性能变差。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "金属材料的塑性变形主要是通过空位的运动来实现的。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "形核率随过冷度的增大而减小，生长率随过冷度的增大而减小。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "大型零件常采用增加过冷度的方法使晶粒细化。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "提高过冷度是细化金属晶粒的一种最佳方法。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "在常温下间隙固溶体能溶解的溶质原子数量是无限的。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "有限固溶体的溶解度与温度有密切关系，一般温度越高，溶解度越小。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "溶质原子分布于溶剂晶格间隙中而形成的固溶体，称为间隙固溶体。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "对于钢铁材料来说，固溶强化的作用是其强化途径的一种。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "合金形成的混合物中各组成部分，仍保持自己原来的晶格和性能。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "金属相图是在实际工作条件下的合金组织状态与温度，成分之间关系的图解。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铁碳合金相图中，当液相冷却到AC线以下结晶出奥氏体，而在CD线以下结晶出一次渗碳体。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "碳素工具钢都是优质或高级优质钢，其含碳量一般大于0.7%。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "晶界属于面缺陷。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "渗碳体的分布，形态在很大程度上会影响钢的性能。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "同素异构转变时，也需要较大的过冷度。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "碳素结构钢都是优质或高级优质钢。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "碳素工具钢的含碳量一般大于1.0%。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铸铁可用于铸造形状复杂而力学性能要求较高的零件。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铸铁的铸造性能比钢好，故常用于铸造形状复杂的工件。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "在铁碳相图中，含碳量大于2.11%的铁碳合金称为铸铁。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "从成分上看，铸铁和钢主要的区别在于铸铁比钢有较高的碳，较低的硅。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铸铁中的硫磷含量比钢的高。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铸铁的耐压，耐磨和减震的功能比钢差。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铸铁中的碳只能以石墨的形式存在。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "白口铁中的碳是以石墨的形式存在。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "白口铁又硬又脆，很难切削加工。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "白口铁可以直接用来制造机器零件。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "灰口铸铁在工业上应用得很广泛。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "可锻铸铁可以锻造。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "球墨铸铁的强度高，韧性好。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "硅是促进石墨化的元素。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铸铁中碳，硅含量越高，析出的石墨量越多，石墨片的尺寸越大。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "钒，铬，钼阻碍石墨化。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "冷却速度对石墨化的影响不大。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "快速冷却会促进白口化。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "灰铸铁组织是有金属基体和片状石墨两部分组成。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "灰铸铁的基体只能是铁素体。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "灰铸铁的强度，塑性和韧性远不如钢。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "铸铁中的石墨越不均匀，割裂基体的作用越严重，铸件的强度，塑性，韧性就越差。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "石墨对抗压强度和硬度的影响大。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "灰铸铁抗压强度和硬度主要取决于基体组织。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "灰铸铁的缺口敏感性比较高。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "灰铸铁的性能只能靠改变金属基体来实现。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "灰铸铁的石墨片越细小，分布越均匀，铸铁的力学性能越高。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "孕育处理后的铸铁的力学性能有很大的提高。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "灰铸铁经过热处理后能改变基体组织。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "灰铸铁经过热处理后能显著改变力学性能。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "灰铸铁的热处理没有任何作用。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "铸件在切削加工的过程中，会引起变形。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "机床的机身和机架要进行去应力退火。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "球墨铸铁可以通过热处理使得其力学性能在较大范围内变化。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "可锻铸铁有较高的强度，并且具有一定的塑性和韧性，可以部分代替锻钢。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}];

module.exports = jsx;