var ltyl = [{
  "type": 1,
  "degree": 2,
  "title": "高炉喷吹煤粉冶炼，炉缸煤气量（ ）。",
  "ans": "B",
  "opts": [{
    "title": "减少",
    "value": "A",
    "checked": 0
  }, {
    "title": "增加",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "炉渣脱硫反应实际是铁中（ ）向渣中转移。",
  "ans": "A",
  "opts": [{
    "title": "[S]",
    "value": "A",
    "checked": 0
  }, {
    "title": "[S2-]",
    "value": "B",
    "checked": 0
  }, {
    "title": "[O]",
    "value": "C",
    "checked": 0
  }, {
    "title": "[O2-]",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "在炼焦过程中煤所含硫的（ ）转入焦炭，其余进入焦炉煤气中。",
  "ans": "B",
  "opts": [{
    "title": "63%-85%",
    "value": "A",
    "checked": 0
  }, {
    "title": "73%-95%",
    "value": "B",
    "checked": 0
  }, {
    "title": "70%-75%",
    "value": "C",
    "checked": 0
  }, {
    "title": "70%-90%",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "生铁含锰超过用户使用标准时应调整锰矿使用量，锰的还原率一般按（ ）考虑。",
  "ans": "A",
  "opts": [{
    "title": "50%",
    "value": "A",
    "checked": 0
  }, {
    "title": "100%",
    "value": "B",
    "checked": 0
  }, {
    "title": "10%",
    "value": "C",
    "checked": 0
  }, {
    "title": "20%",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "碱度低于（ ）的烧结矿称为非自熔性烧结矿。",
  "ans": "B",
  "opts": [{
    "title": "0.9",
    "value": "A",
    "checked": 0
  }, {
    "title": "1.0",
    "value": "B",
    "checked": 0
  }, {
    "title": "0.8",
    "value": "C",
    "checked": 0
  }, {
    "title": "1.1",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "降低热风炉废气温度能（ ）热风炉热效率。",
  "ans": "A",
  "opts": [{
    "title": "提高",
    "value": "A",
    "checked": 0
  }, {
    "title": "降低",
    "value": "B",
    "checked": 0
  }, {
    "title": "维持原来",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉中风口平面以上是（ ）过程。",
  "ans": "A",
  "opts": [{
    "title": "增硅",
    "value": "A",
    "checked": 0
  }, {
    "title": "降硅",
    "value": "B",
    "checked": 0
  }, {
    "title": "不一定",
    "value": "C",
    "checked": 0
  }, {
    "title": "先增后减",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉内哪个区域含硫最高（ ）。",
  "ans": "C",
  "opts": [{
    "title": "块料带",
    "value": "A",
    "checked": 0
  }, {
    "title": "风口前燃烧带",
    "value": "B",
    "checked": 0
  }, {
    "title": "滴落带",
    "value": "C",
    "checked": 0
  }, {
    "title": "渣铁贮存带",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "边缘过重，中心发展时（ ）。",
  "ans": "B",
  "opts": [{
    "title": "风口易灌渣",
    "value": "A",
    "checked": 0
  }, {
    "title": "风口易涌渣",
    "value": "B",
    "checked": 0
  }, {
    "title": "风口与正常时一样",
    "value": "C",
    "checked": 0
  }, {
    "title": "风口易烧坏",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "（ ）即为干燥块焦单位体积的质量。",
  "ans": "C",
  "opts": [{
    "title": "焦炭堆积密度",
    "value": "A",
    "checked": 0
  }, {
    "title": "焦炭真密度",
    "value": "B",
    "checked": 0
  }, {
    "title": "焦炭视密度",
    "value": "C",
    "checked": 0
  }, {
    "title": "以上都不对",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "一般认为使高炉处于（ ）以上的高压下工作，叫做高压操作。",
  "ans": "A",
  "opts": [{
    "title": "0.03mpa",
    "value": "A",
    "checked": 0
  }, {
    "title": "0.05mpa",
    "value": "B",
    "checked": 0
  }, {
    "title": "0.08mpa",
    "value": "C",
    "checked": 0
  }, {
    "title": "0.1mpa",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "软水密闭循环冷却是在（ ）发展起来的新的冷却方式。",
  "ans": "B",
  "opts": [{
    "title": "60年代",
    "value": "A",
    "checked": 0
  }, {
    "title": "60年代后期",
    "value": "B",
    "checked": 0
  }, {
    "title": "70年代",
    "value": "C",
    "checked": 0
  }, {
    "title": "70年代后期",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "提高炉顶压力，对生铁中[Si]含量的影响描述正确的是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "随顶压的提高，生铁中[Si]降低",
    "value": "A",
    "checked": 0
  }, {
    "title": "随顶压的提高，生铁中[Si]含量升高",
    "value": "B",
    "checked": 0
  }, {
    "title": "随顶压的提高，生铁中[Si]含量不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "焦炭的反应性是指焦炭与（ ）等进行化学反应的能力。",
  "ans": "A",
  "opts": [{
    "title": "CO2",
    "value": "A",
    "checked": 0
  }, {
    "title": "铁矿石",
    "value": "B",
    "checked": 0
  }, {
    "title": "碱金属",
    "value": "C",
    "checked": 0
  }, {
    "title": "硫化物",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "磷是有害元素，它使钢铁材料具有（ ）。",
  "ans": "B",
  "opts": [{
    "title": "热脆性",
    "value": "A",
    "checked": 0
  }, {
    "title": "冷脆性",
    "value": "B",
    "checked": 0
  }, {
    "title": "焊接性能变坏",
    "value": "C",
    "checked": 0
  }, {
    "title": "红脆性",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "一般浇注料泥套的寿命为捣打料泥套的（ ）倍。",
  "ans": "A",
  "opts": [{
    "title": "3",
    "value": "A",
    "checked": 0
  }, {
    "title": "2",
    "value": "B",
    "checked": 0
  }, {
    "title": "1",
    "value": "C",
    "checked": 0
  }, {
    "title": "4",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "散料空隙度ε由0.5下降到0.3，阻力因子(1-ε)\/ε3的变化幅度为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "由4升高到23",
    "value": "A",
    "checked": 0
  }, {
    "title": "由4升高到10",
    "value": "B",
    "checked": 0
  }, {
    "title": "由10降低到4",
    "value": "C",
    "checked": 0
  }, {
    "title": "由23降低到4",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "矿石开始软融的温度一般为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "900～1100℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "1000～1200℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "740～900℃",
    "value": "C",
    "checked": 0
  }, {
    "title": "800～900℃",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "根据（ ）含量的不同，把铁碳合金划分为生铁、熟铁和钢。",
  "ans": "C",
  "opts": [{
    "title": "Si",
    "value": "A",
    "checked": 0
  }, {
    "title": "S",
    "value": "B",
    "checked": 0
  }, {
    "title": "C",
    "value": "C",
    "checked": 0
  }, {
    "title": "P",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "焦炭的物理性质包括：机械强度、筛分组成、气孔度、堆密度，其中不重要的是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "机械强度",
    "value": "A",
    "checked": 0
  }, {
    "title": "筛分组成",
    "value": "B",
    "checked": 0
  }, {
    "title": "气孔度",
    "value": "C",
    "checked": 0
  }, {
    "title": "粒度",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "当热风炉助燃风量不足时，应该采用（ ）的燃烧制度。",
  "ans": "B",
  "opts": [{
    "title": "固定煤气量、调节空气量",
    "value": "A",
    "checked": 0
  }, {
    "title": "固定空气量、调节煤气量",
    "value": "B",
    "checked": 0
  }, {
    "title": "煤气量、空气量都不固定",
    "value": "C",
    "checked": 0
  }, {
    "title": "煤气量、空气量都固定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "低料线一小时不能恢复正常时，应减轻焦炭负荷的（ ）。",
  "ans": "B",
  "opts": [{
    "title": "5-8％",
    "value": "A",
    "checked": 0
  }, {
    "title": "10-20％",
    "value": "B",
    "checked": 0
  }, {
    "title": "20-25％",
    "value": "C",
    "checked": 0
  }, {
    "title": "25-30％",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "吨铁消耗的铁矿石中，SiO2含量每增加1％，将使高炉渣量增加（ ）。",
  "ans": "D",
  "opts": [{
    "title": "10～15Kg",
    "value": "A",
    "checked": 0
  }, {
    "title": "20～25Kg",
    "value": "B",
    "checked": 0
  }, {
    "title": "25～30Kg",
    "value": "C",
    "checked": 0
  }, {
    "title": "35～40Kg",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "煤粉中硫的主要存在形式是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "硫酸盐",
    "value": "A",
    "checked": 0
  }, {
    "title": "硫化物",
    "value": "B",
    "checked": 0
  }, {
    "title": "有机硫",
    "value": "C",
    "checked": 0
  }, {
    "title": "氯化物",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉开炉一般都在炉腰以下装净焦、空焦填充，原因是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "炉腰以下不应有未还原矿石，保证开炉炉缸温度充沛",
    "value": "A",
    "checked": 0
  }, {
    "title": "为防止矿石破碎",
    "value": "B",
    "checked": 0
  }, {
    "title": "为高炉顺行",
    "value": "C",
    "checked": 0
  }, {
    "title": "保护炉膛",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "块状带管道行程出现与（ ）有直接关系。",
  "ans": "A",
  "opts": [{
    "title": "炉料流态化",
    "value": "A",
    "checked": 0
  }, {
    "title": "炉料有效质量≤0",
    "value": "B",
    "checked": 0
  }, {
    "title": "液泛因子＞10-3",
    "value": "C",
    "checked": 0
  }, {
    "title": "以上都对",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "风口前焦炭燃烧气化腾出的下料空间占总下料空间的比例约为（ ）％。",
  "ans": "C",
  "opts": [{
    "title": "10～20",
    "value": "A",
    "checked": 0
  }, {
    "title": "20～30",
    "value": "B",
    "checked": 0
  }, {
    "title": "30～40",
    "value": "C",
    "checked": 0
  }, {
    "title": "40～50",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高压操作是指炉顶压力高于（ ）。",
  "ans": "D",
  "opts": [{
    "title": "0.06～0.08MPa",
    "value": "A",
    "checked": 0
  }, {
    "title": "0.1～0.15MPa",
    "value": "B",
    "checked": 0
  }, {
    "title": "0.1MPa",
    "value": "C",
    "checked": 0
  }, {
    "title": "0.03Mpa",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "炉缸煤气最终主要成分是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "CO、H2、N2",
    "value": "A",
    "checked": 0
  }, {
    "title": "CO、CO2、N2",
    "value": "B",
    "checked": 0
  }, {
    "title": "CO2、H2、N2",
    "value": "C",
    "checked": 0
  }, {
    "title": "O2、N2",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉内衬的破损经分析认为主要原因是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "物理作用",
    "value": "A",
    "checked": 0
  }, {
    "title": "化学作用",
    "value": "B",
    "checked": 0
  }, {
    "title": "热力作用",
    "value": "C",
    "checked": 0
  }, {
    "title": "操作因素",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉冶炼过程中的硫主要来自（ ）。",
  "ans": "A",
  "opts": [{
    "title": "焦炭",
    "value": "A",
    "checked": 0
  }, {
    "title": "块矿",
    "value": "B",
    "checked": 0
  }, {
    "title": "烧结矿",
    "value": "C",
    "checked": 0
  }, {
    "title": "熔剂",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "悬料时料尺不动，风压高，顶压（ ）。",
  "ans": "A",
  "opts": [{
    "title": "低",
    "value": "A",
    "checked": 0
  }, {
    "title": "高",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉煤气中可燃成分是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "N2",
    "value": "A",
    "checked": 0
  }, {
    "title": "H2",
    "value": "B",
    "checked": 0
  }, {
    "title": "CO2",
    "value": "C",
    "checked": 0
  }, {
    "title": "O2",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "一般冶炼一吨生铁需要铁矿石量（ ）。",
  "ans": "B",
  "opts": [{
    "title": "1.0t～1.5t",
    "value": "A",
    "checked": 0
  }, {
    "title": "1.5t～2.0t",
    "value": "B",
    "checked": 0
  }, {
    "title": "2.0t～2.5t",
    "value": "C",
    "checked": 0
  }, {
    "title": "2.5t～3.0t",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉对炮泥的性能要求，耐火度要求高于（ ）。",
  "ans": "B",
  "opts": [{
    "title": "1500℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "1650℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "1750℃",
    "value": "C",
    "checked": 0
  }, {
    "title": "1400℃",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉精料的含义包括对入炉原料的精加工和（ ）。",
  "ans": "D",
  "opts": [{
    "title": "选用优质的燃料和熔剂",
    "value": "A",
    "checked": 0
  }, {
    "title": "加强原料的整粒",
    "value": "B",
    "checked": 0
  }, {
    "title": "提高铁品位",
    "value": "C",
    "checked": 0
  }, {
    "title": "采用合理的炉料结构",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "软熔带是高炉透气性最差的部位，决定该区域煤气流动及分布的是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "煤气利用程度",
    "value": "A",
    "checked": 0
  }, {
    "title": "炉料的粒度组成",
    "value": "B",
    "checked": 0
  }, {
    "title": "焦窗面积及其位置形状",
    "value": "C",
    "checked": 0
  }, {
    "title": "无法确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "喷煤量每增加10kg\/t，约降低风口前燃烧温度（ ）。",
  "ans": "B",
  "opts": [{
    "title": "10～20℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "20～25℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "25～30℃",
    "value": "C",
    "checked": 0
  }, {
    "title": "30℃以上",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉内煤气经过 （ ）次分布。",
  "ans": "C",
  "opts": [{
    "title": "一",
    "value": "A",
    "checked": 0
  }, {
    "title": "二",
    "value": "B",
    "checked": 0
  }, {
    "title": "三",
    "value": "C",
    "checked": 0
  }, {
    "title": "四",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "燃烧1t焦炭所需风量一般波动在 （ ）m3\/t。",
  "ans": "B",
  "opts": [{
    "title": "1500～2500",
    "value": "A",
    "checked": 0
  }, {
    "title": "2500～3000",
    "value": "B",
    "checked": 0
  }, {
    "title": "3000～4000",
    "value": "C",
    "checked": 0
  }, {
    "title": "4000～4500",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉内铁矿石从入炉到软熔前分布的区域，称做（ ）。",
  "ans": "D",
  "opts": [{
    "title": "软熔带",
    "value": "A",
    "checked": 0
  }, {
    "title": "滴落带",
    "value": "B",
    "checked": 0
  }, {
    "title": "风口带",
    "value": "C",
    "checked": 0
  }, {
    "title": "块状带",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "粘土砖高炉烘炉时在300℃恒温8～16小时，原因是 （ ）。",
  "ans": "A",
  "opts": [{
    "title": "粘土砖在300℃左右膨胀系数大，砌体易破坏",
    "value": "A",
    "checked": 0
  }, {
    "title": "为延长烘炉",
    "value": "B",
    "checked": 0
  }, {
    "title": "有利于水分蒸发",
    "value": "C",
    "checked": 0
  }, {
    "title": "以上都对",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "矿石含铁量每增加1%，焦比将降低（ ）。",
  "ans": "A",
  "opts": [{
    "title": "2%",
    "value": "A",
    "checked": 0
  }, {
    "title": "4%",
    "value": "B",
    "checked": 0
  }, {
    "title": "6%",
    "value": "C",
    "checked": 0
  }, {
    "title": "8%",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "一般认为高炉散料层ε的在（ ）之间。",
  "ans": "A",
  "opts": [{
    "title": "0.35-0.46",
    "value": "A",
    "checked": 0
  }, {
    "title": "0.231-0.426",
    "value": "B",
    "checked": 0
  }, {
    "title": "0.32-0.45",
    "value": "C",
    "checked": 0
  }, {
    "title": "0.42-0.52",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "低温烧结就是指控制烧结结温度在（ ）的范围内。",
  "ans": "C",
  "opts": [{
    "title": "1000℃～1100℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "1100℃～1180℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "1200℃～1280℃",
    "value": "C",
    "checked": 0
  }, {
    "title": "1300℃～1380℃",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "一般认为焦炭的平均直径为矿石的多少倍时，炉内总的透气性最好（ ）。",
  "ans": "C",
  "opts": [{
    "title": "1倍",
    "value": "A",
    "checked": 0
  }, {
    "title": "2倍",
    "value": "B",
    "checked": 0
  }, {
    "title": "3倍",
    "value": "C",
    "checked": 0
  }, {
    "title": "4倍",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "炉渣的粘度是（ ）泊之间。",
  "ans": "D",
  "opts": [{
    "title": "1～2",
    "value": "A",
    "checked": 0
  }, {
    "title": "10～12",
    "value": "B",
    "checked": 0
  }, {
    "title": "6～10",
    "value": "C",
    "checked": 0
  }, {
    "title": "2～6",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉喷煤后，炉缸风口燃烧带（ ）。",
  "ans": "B",
  "opts": [{
    "title": "不变",
    "value": "A",
    "checked": 0
  }, {
    "title": "延长",
    "value": "B",
    "checked": 0
  }, {
    "title": "缩短",
    "value": "C",
    "checked": 0
  }, {
    "title": "都不是",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "每批料中，矿石与焦炭的比值称为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "焦炭负荷",
    "value": "A",
    "checked": 0
  }, {
    "title": "矿石负荷",
    "value": "B",
    "checked": 0
  }, {
    "title": "硫负荷",
    "value": "C",
    "checked": 0
  }, {
    "title": "熔剂负荷",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "无料钟传动齿轮箱的出水管一般有（ ）。",
  "ans": "D",
  "opts": [{
    "title": "1个",
    "value": "A",
    "checked": 0
  }, {
    "title": "2个",
    "value": "B",
    "checked": 0
  }, {
    "title": "3个",
    "value": "C",
    "checked": 0
  }, {
    "title": "4个",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "根据生铁成分，生铁可分为炼钢生铁和（ ）。",
  "ans": "A",
  "opts": [{
    "title": "铸造生铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "高锰铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "高硫铁",
    "value": "C",
    "checked": 0
  }, {
    "title": "高碳铁",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "根据高炉鼓风和煤气中的（ ）可以计算高炉煤气量。",
  "ans": "B",
  "opts": [{
    "title": "氧气",
    "value": "A",
    "checked": 0
  }, {
    "title": "氮气",
    "value": "B",
    "checked": 0
  }, {
    "title": "一氧化碳",
    "value": "C",
    "checked": 0
  }, {
    "title": "氢气",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉煤气流分布失常的三种形式是：边缘气流过分发展，中心气流过分发展及（ ）。",
  "ans": "A",
  "opts": [{
    "title": "管道行程",
    "value": "A",
    "checked": 0
  }, {
    "title": "炉热",
    "value": "B",
    "checked": 0
  }, {
    "title": "悬料",
    "value": "C",
    "checked": 0
  }, {
    "title": "低料线",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "（ ）供给高炉冶炼的热量最多。",
  "ans": "B",
  "opts": [{
    "title": "热风",
    "value": "A",
    "checked": 0
  }, {
    "title": "焦炭燃烧放热",
    "value": "B",
    "checked": 0
  }, {
    "title": "喷吹燃料燃烧放热",
    "value": "C",
    "checked": 0
  }, {
    "title": "外燃热辐射",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "为提高高炉料柱的透气性，最主要应使矿石和焦炭（ ）",
  "ans": "A",
  "opts": [{
    "title": "热强度高",
    "value": "A",
    "checked": 0
  }, {
    "title": "冷强度高",
    "value": "B",
    "checked": 0
  }, {
    "title": "粒度大",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "在目前我国高炉风温范围内，每提高100℃风温，可降低焦比（ ）kg\/tFe。",
  "ans": "B",
  "opts": [{
    "title": "5～10",
    "value": "A",
    "checked": 0
  }, {
    "title": "15～20",
    "value": "B",
    "checked": 0
  }, {
    "title": "20～30",
    "value": "C",
    "checked": 0
  }, {
    "title": "25～30",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "相对而言（ ）的软融带对炉墙的侵蚀最严重。",
  "ans": "A",
  "opts": [{
    "title": "正V型",
    "value": "A",
    "checked": 0
  }, {
    "title": "倒V型",
    "value": "B",
    "checked": 0
  }, {
    "title": "W型",
    "value": "C",
    "checked": 0
  }, {
    "title": "倒W型",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "煤气上升阻力最大的是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "块状带",
    "value": "A",
    "checked": 0
  }, {
    "title": "滴落带",
    "value": "B",
    "checked": 0
  }, {
    "title": "软熔带",
    "value": "C",
    "checked": 0
  }, {
    "title": "燃烧带",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "在新开炉装料过程中,带风装料情况下,风温应控制在（ ）。",
  "ans": "D",
  "opts": [{
    "title": "250℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "350℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "400℃",
    "value": "C",
    "checked": 0
  }, {
    "title": "300℃",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "焦炭是在回旋区燃烧时将（ ）转入炉渣，所以中间渣的碱度比终渣高。",
  "ans": "B",
  "opts": [{
    "title": "硫分",
    "value": "A",
    "checked": 0
  }, {
    "title": "灰分",
    "value": "B",
    "checked": 0
  }, {
    "title": "固定炭",
    "value": "C",
    "checked": 0
  }, {
    "title": "铁分",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "某铸造铁炉温[Si]＝1.6%,[S]＝0.063%，该铸造铁为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "二类铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "三类铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "号外铁",
    "value": "C",
    "checked": 0
  }, {
    "title": "一类铁",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "焦炭灰分中的碱金属氧化物和（ ） 等都对焦炭的气化反应起催化作用。",
  "ans": "C",
  "opts": [{
    "title": "SiO2",
    "value": "A",
    "checked": 0
  }, {
    "title": "FeO",
    "value": "B",
    "checked": 0
  }, {
    "title": "Fe2O3",
    "value": "C",
    "checked": 0
  }, {
    "title": "CaO",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "大高炉风口循环区的深度(n)与炉缸直径(d)大体的关系为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "n＝0.25d",
    "value": "A",
    "checked": 0
  }, {
    "title": "n＝0.1768d",
    "value": "B",
    "checked": 0
  }, {
    "title": "n＝0.1464d",
    "value": "C",
    "checked": 0
  }, {
    "title": "n＝0.35d",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "在高炉内极易被CO全部还原的元素是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "Ti",
    "value": "A",
    "checked": 0
  }, {
    "title": "Pb",
    "value": "B",
    "checked": 0
  }, {
    "title": "Ni",
    "value": "C",
    "checked": 0
  }, {
    "title": "Zn",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉炉渣中MgO能起脱硫作用，要求MgO含量在（ ）为好。",
  "ans": "A",
  "opts": [{
    "title": "7～12%",
    "value": "A",
    "checked": 0
  }, {
    "title": "12～16%",
    "value": "B",
    "checked": 0
  }, {
    "title": "16～20%",
    "value": "C",
    "checked": 0
  }, {
    "title": "20%以上",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "矿石在炉内的实际堆角为（ ）度。",
  "ans": "C",
  "opts": [{
    "title": "26-29",
    "value": "A",
    "checked": 0
  }, {
    "title": "30-34",
    "value": "B",
    "checked": 0
  }, {
    "title": "36-43",
    "value": "C",
    "checked": 0
  }, {
    "title": "40-47",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "判断生铁牌号是用（ ） 来评定。",
  "ans": "C",
  "opts": [{
    "title": "[S]",
    "value": "A",
    "checked": 0
  }, {
    "title": "[C]",
    "value": "B",
    "checked": 0
  }, {
    "title": "[Si]",
    "value": "C",
    "checked": 0
  }, {
    "title": "[Fe]",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "每昼夜每立方米高炉容积燃烧的焦炭量称为（ ） 。",
  "ans": "C",
  "opts": [{
    "title": "焦比",
    "value": "A",
    "checked": 0
  }, {
    "title": "燃料比",
    "value": "B",
    "checked": 0
  }, {
    "title": "冶炼强度",
    "value": "C",
    "checked": 0
  }, {
    "title": "综合焦比",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "调剂煤量一般开始起作用的时间是冶炼周期的（ ）。",
  "ans": "C",
  "opts": [{
    "title": "0.5",
    "value": "A",
    "checked": 0
  }, {
    "title": "0.6",
    "value": "B",
    "checked": 0
  }, {
    "title": "0.7",
    "value": "C",
    "checked": 0
  }, {
    "title": "0.8",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "通常鼓风温度升高，则带入炉缸的物理热增加，从而使理论燃烧温度升高，反之则降低。一般来说每100℃风温可影响理论燃烧温度（ ）。",
  "ans": "B",
  "opts": [{
    "title": "70℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "80℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "90℃",
    "value": "C",
    "checked": 0
  }, {
    "title": "100℃",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "开炉条件相同的情况下，用枕木填充炉缸的高炉和用焦炭填充炉缸的高炉，哪个开炉焦比更高一些（ ）。",
  "ans": "A",
  "opts": [{
    "title": "枕木填充",
    "value": "A",
    "checked": 0
  }, {
    "title": "焦炭填充",
    "value": "B",
    "checked": 0
  }, {
    "title": "差不多",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "铁水含硫量＜0.03%时，很难用（ ）进一步降低生铁含硫量。",
  "ans": "B",
  "opts": [{
    "title": "碳酸钠",
    "value": "A",
    "checked": 0
  }, {
    "title": "氧化钙",
    "value": "B",
    "checked": 0
  }, {
    "title": "碳化钙",
    "value": "C",
    "checked": 0
  }, {
    "title": "镁焦",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "炉料在炉内停留的时间叫（ ）。",
  "ans": "A",
  "opts": [{
    "title": "冶炼周期",
    "value": "A",
    "checked": 0
  }, {
    "title": "运动周期",
    "value": "B",
    "checked": 0
  }, {
    "title": "停留周期",
    "value": "C",
    "checked": 0
  }, {
    "title": "还原时间",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "在当前高炉冶炼条件下，适宜的直接还原度在（ ）范围内。",
  "ans": "B",
  "opts": [{
    "title": "0.1～0.2",
    "value": "A",
    "checked": 0
  }, {
    "title": "0.2～0.3",
    "value": "B",
    "checked": 0
  }, {
    "title": "0.35～0.4",
    "value": "C",
    "checked": 0
  }, {
    "title": "0.4～0.5",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "熔化温度就是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "液相线温度",
    "value": "A",
    "checked": 0
  }, {
    "title": "煤粉燃烧的温度",
    "value": "B",
    "checked": 0
  }, {
    "title": "焦碳燃烧的温度",
    "value": "C",
    "checked": 0
  }, {
    "title": "能自由流动的温度",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "决定单位生铁燃料消耗量的关键部位是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "固体炉料区",
    "value": "A",
    "checked": 0
  }, {
    "title": "软熔区",
    "value": "B",
    "checked": 0
  }, {
    "title": "焦炭疏松区",
    "value": "C",
    "checked": 0
  }, {
    "title": "风口焦炭循环区",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "下列各种含铁矿物中，（ ）最难还原。",
  "ans": "D",
  "opts": [{
    "title": "磁铁矿",
    "value": "A",
    "checked": 0
  }, {
    "title": "玻璃体",
    "value": "B",
    "checked": 0
  }, {
    "title": "钙铁橄榄石",
    "value": "C",
    "checked": 0
  }, {
    "title": "铁橄榄石",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "炉料中碳酸盐的开始分解温度最高的是（ ） 。",
  "ans": "D",
  "opts": [{
    "title": "FeCO3",
    "value": "A",
    "checked": 0
  }, {
    "title": "MnCO3",
    "value": "B",
    "checked": 0
  }, {
    "title": "MgCO3",
    "value": "C",
    "checked": 0
  }, {
    "title": "CaCO3",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "L04生铁Si标准≤（ ）。",
  "ans": "C",
  "opts": [{
    "title": "0.35",
    "value": "A",
    "checked": 0
  }, {
    "title": "0.4",
    "value": "B",
    "checked": 0
  }, {
    "title": "0.45",
    "value": "C",
    "checked": 0
  }, {
    "title": "0.5",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "煤气中每增加1%的机械水，t理随之降低（ ）℃。",
  "ans": "B",
  "opts": [{
    "title": "8.5",
    "value": "A",
    "checked": 0
  }, {
    "title": "13",
    "value": "B",
    "checked": 0
  }, {
    "title": "16",
    "value": "C",
    "checked": 0
  }, {
    "title": "24",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "料速由快转慢，炉温由（ ）。",
  "ans": "B",
  "opts": [{
    "title": "热转凉",
    "value": "A",
    "checked": 0
  }, {
    "title": "凉转热",
    "value": "B",
    "checked": 0
  }, {
    "title": "基本不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "矿石与焦炭在炉喉的分布状况将（ ）。",
  "ans": "C",
  "opts": [{
    "title": "只影响煤气的分布",
    "value": "A",
    "checked": 0
  }, {
    "title": "只影响温度分布",
    "value": "B",
    "checked": 0
  }, {
    "title": "影响煤气流和温度的分布以及软熔带的形状",
    "value": "C",
    "checked": 0
  }, {
    "title": "都不影响",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "增加喷煤量，风口前理论燃烧温度将（ ） 。",
  "ans": "B",
  "opts": [{
    "title": "提高冶炼强度",
    "value": "A",
    "checked": 0
  }, {
    "title": "降低",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "以上都不对",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "炼钢用生铁和铸造用生铁的代号分别是（ ） 。",
  "ans": "B",
  "opts": [{
    "title": "LG,ZZ",
    "value": "A",
    "checked": 0
  }, {
    "title": "L,Z",
    "value": "B",
    "checked": 0
  }, {
    "title": "LI,ZH",
    "value": "C",
    "checked": 0
  }, {
    "title": "G，Z",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉内碱金属的危害根源在于它们的（ ）。",
  "ans": "A",
  "opts": [{
    "title": "循环和富集",
    "value": "A",
    "checked": 0
  }, {
    "title": "挥发",
    "value": "B",
    "checked": 0
  }, {
    "title": "蒸发",
    "value": "C",
    "checked": 0
  }, {
    "title": "以上都不是",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "生产中调整风口直径和长度，属于（ ）制度的调剂。",
  "ans": "B",
  "opts": [{
    "title": "装料",
    "value": "A",
    "checked": 0
  }, {
    "title": "送风",
    "value": "B",
    "checked": 0
  }, {
    "title": "造渣",
    "value": "C",
    "checked": 0
  }, {
    "title": "热",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "“矮胖”型高炉和多风口，有利于（ ），有利于顺行。",
  "ans": "A",
  "opts": [{
    "title": "强化冶炼",
    "value": "A",
    "checked": 0
  }, {
    "title": "高炉长寿",
    "value": "B",
    "checked": 0
  }, {
    "title": "降低焦比",
    "value": "C",
    "checked": 0
  }, {
    "title": "提高鼓风动能",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "炉身角小有利于（ ）。",
  "ans": "B",
  "opts": [{
    "title": "中心气流发展",
    "value": "A",
    "checked": 0
  }, {
    "title": "边沿气流发展",
    "value": "B",
    "checked": 0
  }, {
    "title": "对煤气流分布没影响",
    "value": "C",
    "checked": 0
  }, {
    "title": "均衡发展",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "1Kg湿份相当于干风量（ ）m3。",
  "ans": "C",
  "opts": [{
    "title": "2.645",
    "value": "A",
    "checked": 0
  }, {
    "title": "2.837",
    "value": "B",
    "checked": 0
  }, {
    "title": "2.963",
    "value": "C",
    "checked": 0
  }, {
    "title": "2.988",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "据试验，空气中氧的浓度每增加1%，焦炭着火温度大致可降低（ ）。",
  "ans": "B",
  "opts": [{
    "title": "5.5-7.5℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "6.5-8.5℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "7.5-9.5℃",
    "value": "C",
    "checked": 0
  }, {
    "title": "8.5-10.5℃",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "普通炉渣的熔化温度范围为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "1100～1200℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "1200～1300℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "1300～1400℃",
    "value": "C",
    "checked": 0
  }, {
    "title": "900～1000℃",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "在高炉操作线中，ks表示炉身效率，现代大型高炉已达（ ）以上。",
  "ans": "D",
  "opts": [{
    "title": "0.80",
    "value": "A",
    "checked": 0
  }, {
    "title": "0.85",
    "value": "B",
    "checked": 0
  }, {
    "title": "0.90",
    "value": "C",
    "checked": 0
  }, {
    "title": "0.95",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "焦炭强度差会影响料柱透气性，导致风渣口烧坏和（ ）。",
  "ans": "C",
  "opts": [{
    "title": "炉温向凉",
    "value": "A",
    "checked": 0
  }, {
    "title": "产量升高",
    "value": "B",
    "checked": 0
  }, {
    "title": "炉缸堆积",
    "value": "C",
    "checked": 0
  }, {
    "title": "铁口过浅",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "喷吹煤粉后高炉压差（ ）。",
  "ans": "A",
  "opts": [{
    "title": "升高",
    "value": "A",
    "checked": 0
  }, {
    "title": "降低",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "喷吹煤粉后应（ ）富氧量。",
  "ans": "A",
  "opts": [{
    "title": "提高",
    "value": "A",
    "checked": 0
  }, {
    "title": "减少",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "含碳量低0.2%的钢铁称为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "生铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "钢",
    "value": "B",
    "checked": 0
  }, {
    "title": "熟铁",
    "value": "C",
    "checked": 0
  }, {
    "title": "铸铁",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "目前，提高铁的直接还原度一般将使高炉焦比（ ） 。",
  "ans": "A",
  "opts": [{
    "title": "提高",
    "value": "A",
    "checked": 0
  }, {
    "title": "降低",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "以上都不对",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "正常铁口深度的确定依据是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "炉底侵蚀程度?",
    "value": "A",
    "checked": 0
  }, {
    "title": "铁口角度",
    "value": "B",
    "checked": 0
  }, {
    "title": "铁口区域炉墙厚度",
    "value": "C",
    "checked": 0
  }, {
    "title": "铁口深度",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉去硫比炼钢去硫（ ）。",
  "ans": "B",
  "opts": [{
    "title": "困难",
    "value": "A",
    "checked": 0
  }, {
    "title": "容易",
    "value": "B",
    "checked": 0
  }, {
    "title": "一样",
    "value": "C",
    "checked": 0
  }, {
    "title": "不确定",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高碱度烧结矿的主要优点是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "产量高",
    "value": "A",
    "checked": 0
  }, {
    "title": "粉末少",
    "value": "B",
    "checked": 0
  }, {
    "title": "还原性好",
    "value": "C",
    "checked": 0
  }, {
    "title": "焦比低",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "空料线停炉时，随着料面下降，煤气中CO2含量的变化规律是（ ）。",
  "ans": "D",
  "opts": [{
    "title": "逐渐下降",
    "value": "A",
    "checked": 0
  }, {
    "title": "逐渐上升",
    "value": "B",
    "checked": 0
  }, {
    "title": "先升后降",
    "value": "C",
    "checked": 0
  }, {
    "title": "先降后升",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "产生液泛现象的泡沫渣与下列哪种物质过多有关（ ）。",
  "ans": "D",
  "opts": [{
    "title": "CaO",
    "value": "A",
    "checked": 0
  }, {
    "title": "SiO2",
    "value": "B",
    "checked": 0
  }, {
    "title": "MnO",
    "value": "C",
    "checked": 0
  }, {
    "title": "FeO",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "焦比是每炼（ ）吨铁需要的焦炭量。",
  "ans": "A",
  "opts": [{
    "title": "1",
    "value": "A",
    "checked": 0
  }, {
    "title": "2",
    "value": "B",
    "checked": 0
  }, {
    "title": "1.5",
    "value": "C",
    "checked": 0
  }, {
    "title": "100",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "关于炉料中结晶水的分解说法正确的一组是（ ）。",
  "ans": "D",
  "opts": [{
    "title": "分解吸收煤气余热",
    "value": "A",
    "checked": 0
  }, {
    "title": "可降低焦比",
    "value": "B",
    "checked": 0
  }, {
    "title": "减少炉尘吹出",
    "value": "C",
    "checked": 0
  }, {
    "title": "使炉料粉化",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "下面（ ）不是高炉煤气组成成分。",
  "ans": "A",
  "opts": [{
    "title": "CH4",
    "value": "A",
    "checked": 0
  }, {
    "title": "CO和CO2",
    "value": "B",
    "checked": 0
  }, {
    "title": "N2",
    "value": "C",
    "checked": 0
  }, {
    "title": "H2",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "风口面积的调整（ ）。",
  "ans": "C",
  "opts": [{
    "title": "是根据铁品种定",
    "value": "A",
    "checked": 0
  }, {
    "title": "为了脱硫",
    "value": "B",
    "checked": 0
  }, {
    "title": "下部调剂的主要手段",
    "value": "C",
    "checked": 0
  }, {
    "title": "提高产量",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "根据一维的散料层中的还原过程的数学模型的计算结果，还原剂中H2的最佳比例为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "10%",
    "value": "A",
    "checked": 0
  }, {
    "title": "20%",
    "value": "B",
    "checked": 0
  }, {
    "title": "30%",
    "value": "C",
    "checked": 0
  }, {
    "title": "40%",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "喷吹燃料产生的还原性气体最多的是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "重油",
    "value": "A",
    "checked": 0
  }, {
    "title": "天然气",
    "value": "B",
    "checked": 0
  }, {
    "title": "煤粉",
    "value": "C",
    "checked": 0
  }, {
    "title": "焦粉",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "一般高炉槽下称量报警时的终止值是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "95%",
    "value": "A",
    "checked": 0
  }, {
    "title": "100%",
    "value": "B",
    "checked": 0
  }, {
    "title": "105%",
    "value": "C",
    "checked": 0
  }, {
    "title": "200%",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "热风炉传热方式以（ ）为主。",
  "ans": "B",
  "opts": [{
    "title": "传导",
    "value": "A",
    "checked": 0
  }, {
    "title": "对流",
    "value": "B",
    "checked": 0
  }, {
    "title": "辐射",
    "value": "C",
    "checked": 0
  }, {
    "title": "热传递",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "就世界范围而言，贮藏量最多且是炼铁的主要铁矿石资源（ ）",
  "ans": "B",
  "opts": [{
    "title": "磁铁矿",
    "value": "A",
    "checked": 0
  }, {
    "title": "赤铁矿",
    "value": "B",
    "checked": 0
  }, {
    "title": "褐铁矿",
    "value": "C",
    "checked": 0
  }, {
    "title": "菱铁矿",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "烧结过程中，（ ）层温度最高。",
  "ans": "B",
  "opts": [{
    "title": "烧结矿",
    "value": "A",
    "checked": 0
  }, {
    "title": "燃烧",
    "value": "B",
    "checked": 0
  }, {
    "title": "预热",
    "value": "C",
    "checked": 0
  }, {
    "title": "过湿",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "下列哪种软熔带的煤气利用较好（ ）",
  "ans": "A",
  "opts": [{
    "title": "倒V形",
    "value": "A",
    "checked": 0
  }, {
    "title": "V形",
    "value": "B",
    "checked": 0
  }, {
    "title": "W形",
    "value": "C",
    "checked": 0
  }, {
    "title": "倒W形",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "在风量一定条件下，扩大风口直径，燃烧带（ ）",
  "ans": "B",
  "opts": [{
    "title": "扩大",
    "value": "A",
    "checked": 0
  }, {
    "title": "缩小",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "先扩大后缩小",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "提高风温或富氧，可使燃烧带（ ）",
  "ans": "B",
  "opts": [{
    "title": "扩大",
    "value": "A",
    "checked": 0
  }, {
    "title": "缩小",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }, {
    "title": "先扩大后缩小",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "降低直接还原度将使燃料消耗（ ）",
  "ans": "B",
  "opts": [{
    "title": "增加",
    "value": "A",
    "checked": 0
  }, {
    "title": "减小",
    "value": "B",
    "checked": 0
  }, {
    "title": "没影响",
    "value": "C",
    "checked": 0
  }, {
    "title": "先扩大后缩小",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "降低炉渣脱硫能力的手段是（ ）",
  "ans": "C",
  "opts": [{
    "title": "高碱度",
    "value": "A",
    "checked": 0
  }, {
    "title": "高温度",
    "value": "B",
    "checked": 0
  }, {
    "title": "高FeO",
    "value": "C",
    "checked": 0
  }, {
    "title": "低FeO",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "能促进生铁中含碳量增加的元素有（ ）",
  "ans": "A",
  "opts": [{
    "title": "Mn",
    "value": "A",
    "checked": 0
  }, {
    "title": "Si",
    "value": "B",
    "checked": 0
  }, {
    "title": "P",
    "value": "C",
    "checked": 0
  }, {
    "title": "S",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "属于粗除尘器的有（ ）",
  "ans": "A",
  "opts": [{
    "title": "重力除尘器",
    "value": "A",
    "checked": 0
  }, {
    "title": "文式管",
    "value": "B",
    "checked": 0
  }, {
    "title": "布袋除尘器",
    "value": "C",
    "checked": 0
  }, {
    "title": "电除尘器",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "生矿中最易还原的是（ ）",
  "ans": "C",
  "opts": [{
    "title": "赤铁矿",
    "value": "A",
    "checked": 0
  }, {
    "title": "磁铁矿",
    "value": "B",
    "checked": 0
  }, {
    "title": "褐铁矿",
    "value": "C",
    "checked": 0
  }, {
    "title": "菱铁矿",
    "value": "D",
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "短焰燃烧器实现短焰又不回火，（ ）是关键。",
  "ans": "AC",
  "opts": [{
    "title": "燃烧口的大小",
    "value": 0,
    "checked": 0
  }, {
    "title": "燃烧器的高度",
    "value": 1,
    "checked": 0
  }, {
    "title": "流速",
    "value": 2,
    "checked": 0
  }, {
    "title": "空气过剩系数",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "炼钢与炼铁过程相比，（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "钢渣的温度高",
    "value": 0,
    "checked": 0
  }, {
    "title": "钢渣的碱度高",
    "value": 1,
    "checked": 0
  }, {
    "title": "钢渣中（FeO）高",
    "value": 2,
    "checked": 0
  }, {
    "title": "钢渣与钢水的硫的理论分配系数高",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "化学反应的平衡常数与（ ）有关。",
  "ans": "AD",
  "opts": [{
    "title": "温度",
    "value": 0,
    "checked": 0
  }, {
    "title": "压力",
    "value": 1,
    "checked": 0
  }, {
    "title": "气体流速",
    "value": 2,
    "checked": 0
  }, {
    "title": "过剩系数",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "关于高炉内碳酸盐分解的规律，叙述错误的是（ ）。",
  "ans": "BCD",
  "opts": [{
    "title": "碳酸盐的分解压随温度的升高而增大",
    "value": 0,
    "checked": 0
  }, {
    "title": "碳酸盐的分解压越大，碳酸盐的稳定性越好",
    "value": 1,
    "checked": 0
  }, {
    "title": "当碳酸盐的分解压超过炉内煤气总压时，开始分解",
    "value": 2,
    "checked": 0
  }, {
    "title": "当碳酸盐的分解压超过炉内煤气的CO2分压压力时激烈分解即化学沸腾",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "下列措施（ ）使炉顶温度下降。",
  "ans": "ABC",
  "opts": [{
    "title": "富氧鼓风",
    "value": 0,
    "checked": 0
  }, {
    "title": "降低燃料比",
    "value": 1,
    "checked": 0
  }, {
    "title": "增大焦炭负荷",
    "value": 2,
    "checked": 0
  }, {
    "title": "喷煤",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "炉渣成分来自以下几个方面（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "矿石中的脉石",
    "value": 0,
    "checked": 0
  }, {
    "title": "焦炭灰分",
    "value": 1,
    "checked": 0
  }, {
    "title": "熔剂氧化物",
    "value": 2,
    "checked": 0
  }, {
    "title": "被浸的炉衬",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "管道行程的征兆是（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "风压下降、风量自动增加",
    "value": 0,
    "checked": 0
  }, {
    "title": "料尺工作不均，出现滑尺、埋尺、停滞、塌落等假尺现象",
    "value": 1,
    "checked": 0
  }, {
    "title": "炉喉煤气曲线不规则，管道处CO2值低",
    "value": 2,
    "checked": 0
  }, {
    "title": "瓦斯灰（炉尘）吹出量明显减少",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "上部管道行程的处理措施叙述正确的是（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "适当减风，炉热引起的管道可以降风温",
    "value": 0,
    "checked": 0
  }, {
    "title": "改变布料，将几批料的炉料堆尖放在管道位置，堵塞管道",
    "value": 1,
    "checked": 0
  }, {
    "title": "用高压、常压转换的方法重新合理分布煤气流",
    "value": 2,
    "checked": 0
  }, {
    "title": "其他调整不见效时，应休风处理、破坏管道行程",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "风量调节的原则有（ ）。",
  "ans": "BD",
  "opts": [{
    "title": "控制料批",
    "value": 0,
    "checked": 0
  }, {
    "title": "减风一次到位，加风应和缓",
    "value": 1,
    "checked": 0
  }, {
    "title": "稳定气流",
    "value": 2,
    "checked": 0
  }, {
    "title": "一般只宜在其他手段犹不足时才采取",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "高炉对喷吹煤的性能要求为（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "煤的灰分要低",
    "value": 0,
    "checked": 0
  }, {
    "title": "煤的硫分要低",
    "value": 1,
    "checked": 0
  }, {
    "title": "煤的燃烧性能要好，其着火温度低，反应性强。",
    "value": 2,
    "checked": 0
  }, {
    "title": "可磨性要差",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "降低铁水[S]的措施有（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "降低硫负荷",
    "value": 0,
    "checked": 0
  }, {
    "title": "增大硫的挥发量",
    "value": 1,
    "checked": 0
  }, {
    "title": "加大渣量",
    "value": 2,
    "checked": 0
  }, {
    "title": "降低硫的分配系数",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "降低直接还原度的方法包括（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "改善铁矿石的还原度",
    "value": 0,
    "checked": 0
  }, {
    "title": "炼铁工序能耗是指冶炼每吨延长煤气与矿石的接触时间",
    "value": 1,
    "checked": 0
  }, {
    "title": "扩大高炉的中部区域",
    "value": 2,
    "checked": 0
  }, {
    "title": "喷吹含H2的燃料",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "炉渣中含有一定数量的MgO，能提高炉渣的（ ）。",
  "ans": "BC",
  "opts": [{
    "title": "熔化温度",
    "value": 0,
    "checked": 0
  }, {
    "title": "流动性",
    "value": 1,
    "checked": 0
  }, {
    "title": "脱硫能力",
    "value": 2,
    "checked": 0
  }, {
    "title": "脱磷能力",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "冶金学按研究的领域分为两类是（ ）。",
  "ans": "AB",
  "opts": [{
    "title": "物理冶金学",
    "value": 0,
    "checked": 0
  }, {
    "title": "化学冶金学",
    "value": 1,
    "checked": 0
  }, {
    "title": "有色冶金",
    "value": 2,
    "checked": 0
  }, {
    "title": "黑色冶金",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "高炉强化冶炼后风口布局原则（ ）。",
  "ans": "BCD",
  "opts": [{
    "title": "炉墙结厚的部位采用大风口、长风口",
    "value": 0,
    "checked": 0
  }, {
    "title": "铁口难维护时，铁口两侧用小风口、长风口",
    "value": 1,
    "checked": 0
  }, {
    "title": "煤气流分布不均，下料快的方位应缩小风口面积",
    "value": 2,
    "checked": 0
  }, {
    "title": "炉缸工作不均匀时，进风少的区域使用大风口",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "空料线停炉过程中煤气中CO2的含量与料线的关系式（ ）。",
  "ans": "AD",
  "opts": [{
    "title": "可根据CO2的含量判断料线",
    "value": 0,
    "checked": 0
  }, {
    "title": "CO2曲线拐点在炉身下部，标志间接还原结束",
    "value": 1,
    "checked": 0
  }, {
    "title": "料线降至风口中心线时CO2达到18-20%，出最后一次铁后停炉休风",
    "value": 2,
    "checked": 0
  }, {
    "title": "料线降至风口附近时CO2达到15-18%，出最后一次铁后停炉休风",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "表示热制度的指标是（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "铁水温度",
    "value": 0,
    "checked": 0
  }, {
    "title": "Si",
    "value": 1,
    "checked": 0
  }, {
    "title": "Ti",
    "value": 2,
    "checked": 0
  }, {
    "title": "P",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "高炉内FeO是通过（ ）方式被还原。",
  "ans": "ABCD",
  "opts": [{
    "title": "被气体H2间接还原",
    "value": 0,
    "checked": 0
  }, {
    "title": "借助碳素溶解损失反应和水煤气反应被C直接还原",
    "value": 1,
    "checked": 0
  }, {
    "title": "含FeO的液态炉渣与焦炭接触时或与铁水中饱和碳发生反应。",
    "value": 2,
    "checked": 0
  }, {
    "title": "被气体CO间接还原",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "高炉强化冶炼后风口布局原则是（ ）。",
  "ans": "ACD",
  "opts": [{
    "title": "炉墙结厚的部位采用大风口、短风口",
    "value": 0,
    "checked": 0
  }, {
    "title": "铁口难开维护时，铁口两侧采用小风口、短风口",
    "value": 1,
    "checked": 0
  }, {
    "title": "煤气流分布不均，炉料偏行，下料快的方位应缩小风口面积",
    "value": 2,
    "checked": 0
  }, {
    "title": "炉缸工作不均匀时，进风少的区域采用大风口",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "全硫的测定方法有（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "质量法",
    "value": 0,
    "checked": 0
  }, {
    "title": "库仑滴定法",
    "value": 1,
    "checked": 0
  }, {
    "title": "高温燃烧中和法",
    "value": 2,
    "checked": 0
  }, {
    "title": "化学分析法",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "评价铁矿石质量应从（?）等方面进行。",
  "ans": "ABCD",
  "opts": [{
    "title": "矿石含铁量",
    "value": 0,
    "checked": 0
  }, {
    "title": "脉石的化学成分",
    "value": 1,
    "checked": 0
  }, {
    "title": "矿石中的有害杂质",
    "value": 2,
    "checked": 0
  }, {
    "title": "矿石的还原性",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "合理炉料结构根据（ ）来确定。",
  "ans": "ABCD",
  "opts": [{
    "title": "根据资源、矿石加工技术水平",
    "value": 0,
    "checked": 0
  }, {
    "title": "设备状况",
    "value": 1,
    "checked": 0
  }, {
    "title": "造块成品矿的价格及其冶金性能",
    "value": 2,
    "checked": 0
  }, {
    "title": "结合具体条件通过试验、论证后",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "下列哪些是富氧后的冶炼特征（ ）。",
  "ans": "ABD",
  "opts": [{
    "title": "理论燃烧温度升高",
    "value": 0,
    "checked": 0
  }, {
    "title": "煤气量减少",
    "value": 1,
    "checked": 0
  }, {
    "title": "间接还原扩大",
    "value": 2,
    "checked": 0
  }, {
    "title": "煤气发热值提高",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "生产过程中，应严密控制的关键性环节为（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "送风条件",
    "value": 0,
    "checked": 0
  }, {
    "title": "软融区的位置、形状、尺寸",
    "value": 1,
    "checked": 0
  }, {
    "title": "固体炉料区的工作状态",
    "value": 2,
    "checked": 0
  }, {
    "title": "设备状况",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "喷吹燃料后对冶炼影响的是（ ）。",
  "ans": "ABD",
  "opts": [{
    "title": "顶温升高",
    "value": 0,
    "checked": 0
  }, {
    "title": "还原改善",
    "value": 1,
    "checked": 0
  }, {
    "title": "生铁质量变差",
    "value": 2,
    "checked": 0
  }, {
    "title": "理论燃烧温度降低",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "高炉强化冶炼的基本途径是（ ）。",
  "ans": "AD",
  "opts": [{
    "title": "提高冶炼强度",
    "value": 0,
    "checked": 0
  }, {
    "title": "降低冶炼强度",
    "value": 1,
    "checked": 0
  }, {
    "title": "提高焦比",
    "value": 2,
    "checked": 0
  }, {
    "title": "降低焦比",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "生铁的形成过程主要是还原出来的金属铁和（ ）等元素的溶入。",
  "ans": "ABCD",
  "opts": [{
    "title": "C",
    "value": 0,
    "checked": 0
  }, {
    "title": "Si",
    "value": 1,
    "checked": 0
  }, {
    "title": "Mn",
    "value": 2,
    "checked": 0
  }, {
    "title": "P",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "炉缸燃烧反应在高炉冶炼中的作用有（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "提供热量",
    "value": 0,
    "checked": 0
  }, {
    "title": "提供自由空间",
    "value": 1,
    "checked": 0
  }, {
    "title": "提供还原剂",
    "value": 2,
    "checked": 0
  }, {
    "title": "影响生铁质量",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "（ ）对炉渣的脱硫反应有利。",
  "ans": "ABC",
  "opts": [{
    "title": "提高温度",
    "value": 0,
    "checked": 0
  }, {
    "title": "提高[Si]",
    "value": 1,
    "checked": 0
  }, {
    "title": "提高[Mn]",
    "value": 2,
    "checked": 0
  }, {
    "title": "提高渣氧势",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "目前计算理论焦比的方法有（ ）计算法。",
  "ans": "ABCD",
  "opts": [{
    "title": "联合",
    "value": 0,
    "checked": 0
  }, {
    "title": "里斯特",
    "value": 1,
    "checked": 0
  }, {
    "title": "工程",
    "value": 2,
    "checked": 0
  }, {
    "title": "区域热平衡",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "影响炉渣脱硫能力的因素（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "炉渣碱度",
    "value": 0,
    "checked": 0
  }, {
    "title": "渣铁温度",
    "value": 1,
    "checked": 0
  }, {
    "title": "硫在生铁中的活度",
    "value": 2,
    "checked": 0
  }, {
    "title": "高炉操作",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "高炉不具备脱磷能力的原因包括（ ）。",
  "ans": "ACD",
  "opts": [{
    "title": "磷在原料中以磷酸盐的形式存在，炉内有SiO2的存在，置换出P2O5，使磷还原变容易",
    "value": 0,
    "checked": 0
  }, {
    "title": "P2O5不易挥发，与C接触后难还原",
    "value": 1,
    "checked": 0
  }, {
    "title": "还原出的P与Fe生成Fe3P和Fe2P，有利于磷的还原",
    "value": 2,
    "checked": 0
  }, {
    "title": "P容易挥发，促进还原反应的进行",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "高风温操作后煤气中CO利用率提高，原因在于（ ）。",
  "ans": "AB",
  "opts": [{
    "title": "间接还原区扩大",
    "value": 0,
    "checked": 0
  }, {
    "title": "焦比降低",
    "value": 1,
    "checked": 0
  }, {
    "title": "炉身温度升高",
    "value": 2,
    "checked": 0
  }, {
    "title": "料柱透气性差，煤气在炉内停留时间延长",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "碰撞点的位置与下列因素有关的是（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "炉料性质",
    "value": 0,
    "checked": 0
  }, {
    "title": "炉喉间隙",
    "value": 1,
    "checked": 0
  }, {
    "title": "大钟边缘伸出漏斗的长度",
    "value": 2,
    "checked": 0
  }, {
    "title": "溜槽倾动距",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "高炉内的还原反应基本分为两大类（ ）。",
  "ans": "AB",
  "opts": [{
    "title": "间接还原",
    "value": 0,
    "checked": 0
  }, {
    "title": "直接还原",
    "value": 1,
    "checked": 0
  }, {
    "title": "还原反应",
    "value": 2,
    "checked": 0
  }, {
    "title": "氧化反应",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "钢铁生产过程由矿石到钢材可分为两个流程是（ ）。",
  "ans": "AB",
  "opts": [{
    "title": "长流程",
    "value": 0,
    "checked": 0
  }, {
    "title": "短流程",
    "value": 1,
    "checked": 0
  }, {
    "title": "基本流程",
    "value": 2,
    "checked": 0
  }, {
    "title": "非基本流程",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "关于烧结矿中四元系铁酸钙的说法正确的是（ ）。",
  "ans": "ABD",
  "opts": [{
    "title": "可提高烧结矿的强度",
    "value": 0,
    "checked": 0
  }, {
    "title": "改善烧结矿的还原性",
    "value": 1,
    "checked": 0
  }, {
    "title": "微观结构为片状",
    "value": 2,
    "checked": 0
  }, {
    "title": "微观结构为针状",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "两把探尺相差超过0.5米，谓偏料。长期偏料应检查下列情况（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "探尺零位是否准确",
    "value": 0,
    "checked": 0
  }, {
    "title": "炉身是否结瘤",
    "value": 1,
    "checked": 0
  }, {
    "title": "布料器运转是否正常，大、小料钟中心位置是否偏移",
    "value": 2,
    "checked": 0
  }, {
    "title": "炉喉钢砖是否严重变形、损坏，查出问题及时纠正和处理",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "影响矿石还原性的主要因素有（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "矿石本身的致密程度",
    "value": 0,
    "checked": 0
  }, {
    "title": "矿石本身的粒度",
    "value": 1,
    "checked": 0
  }, {
    "title": "气孔度",
    "value": 2,
    "checked": 0
  }, {
    "title": "矿石品位",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "高炉送风制度应考虑的原则是（ ）。",
  "ans": "ACD",
  "opts": [{
    "title": "稳定使用合理的大风量是选择送风制度的出发点",
    "value": 0,
    "checked": 0
  }, {
    "title": "应与料柱透气性相适应，维持一个较高的全压差",
    "value": 1,
    "checked": 0
  }, {
    "title": "形成良好炉缸工作状态，得到合理煤气分布",
    "value": 2,
    "checked": 0
  }, {
    "title": "充分发挥鼓风机能力",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "理查特区域热平衡图解根据高炉内（ ）特点创立的。",
  "ans": "AB",
  "opts": [{
    "title": "热交换",
    "value": 0,
    "checked": 0
  }, {
    "title": "热平衡",
    "value": 1,
    "checked": 0
  }, {
    "title": "物料平衡",
    "value": 2,
    "checked": 0
  }, {
    "title": "化学平衡",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "第三种编制全炉热平衡的方法，其热收入项只限于（ ）。",
  "ans": "AD",
  "opts": [{
    "title": "燃烧带内碳氧化成CO放出的热量",
    "value": 0,
    "checked": 0
  }, {
    "title": "直接还原中C氧化成CO放出的热量",
    "value": 1,
    "checked": 0
  }, {
    "title": "间接还原中CO氧化成CO2放出的热量",
    "value": 2,
    "checked": 0
  }, {
    "title": "热风带入的热量",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "关于富氧鼓风那些描述正确（ ）。",
  "ans": "ABD",
  "opts": [{
    "title": "单位生铁煤气生成量减少，允许提高冶炼强度，增加产量",
    "value": 0,
    "checked": 0
  }, {
    "title": "单位重量焦炭燃烧生成的煤气量减少，可改善炉内热能利用，减低炉顶煤气温度",
    "value": 1,
    "checked": 0
  }, {
    "title": "单位生铁煤气生成量减少，炉顶煤气发热值降低",
    "value": 2,
    "checked": 0
  }, {
    "title": "理论燃烧温度升高，炉缸热量集中，利于冶炼反应进行",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "可引起风口前燃烧带扩张的因素有（ ）。",
  "ans": "BD",
  "opts": [{
    "title": "提高风温",
    "value": 0,
    "checked": 0
  }, {
    "title": "提高风量",
    "value": 1,
    "checked": 0
  }, {
    "title": "提高富氧量",
    "value": 2,
    "checked": 0
  }, {
    "title": "加湿鼓风",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "未燃的喷吹煤粉在高炉内的行为包括（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "参与碳素气化反应与渗碳反应",
    "value": 0,
    "checked": 0
  }, {
    "title": "混在渣中，影响渣的流动性",
    "value": 1,
    "checked": 0
  }, {
    "title": "沉积在软熔带和料柱中，恶化透气性",
    "value": 2,
    "checked": 0
  }, {
    "title": "随煤气逸出炉外",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "衡量和评价炉前操作水平的主要指标是（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "出铁正点率",
    "value": 0,
    "checked": 0
  }, {
    "title": "铁口合格率",
    "value": 1,
    "checked": 0
  }, {
    "title": "铁量差",
    "value": 2,
    "checked": 0
  }, {
    "title": "上下渣比",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "煤粉的燃烧分为三个阶段（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "加热",
    "value": 0,
    "checked": 0
  }, {
    "title": "挥发分挥发",
    "value": 1,
    "checked": 0
  }, {
    "title": "燃烧",
    "value": 2,
    "checked": 0
  }, {
    "title": "干馏",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "生铁进行大量渗碳的部位是（ ）。",
  "ans": "CD",
  "opts": [{
    "title": "炉身",
    "value": 0,
    "checked": 0
  }, {
    "title": "炉腰",
    "value": 1,
    "checked": 0
  }, {
    "title": "炉缸",
    "value": 2,
    "checked": 0
  }, {
    "title": "炉腹",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "关于高炉内热交换的过程，描述正确的有（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "高炉内的热量传输以对流传热为主，只是在高温区才考虑辐射传热；在凝聚相内则进行传导传热",
    "value": 0,
    "checked": 0
  }, {
    "title": "在高炉的上部炉料的水当量小于煤气的水当量",
    "value": 1,
    "checked": 0
  }, {
    "title": "在高炉的下部，炉料的水当量远远大于煤气的水当量",
    "value": 2,
    "checked": 0
  }, {
    "title": "在高炉中部有一段炉料的水当量约等于煤气的水当量，但此时一些放热与吸热过程同时激烈进行，维持了炉料温度不变化",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "初渣中高FeO的低熔点化合物量很大时，会造成（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "直接还原增加",
    "value": 0,
    "checked": 0
  }, {
    "title": "软熔带位置升高",
    "value": 1,
    "checked": 0
  }, {
    "title": "煤气阻力增加",
    "value": 2,
    "checked": 0
  }, {
    "title": "软熔带高度增加",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "热风温度每提高100℃，对焦比和产量的影响正确的是（ ）。",
  "ans": "AD",
  "opts": [{
    "title": "焦比降低4－7％",
    "value": 0,
    "checked": 0
  }, {
    "title": "焦比降低3－6％",
    "value": 1,
    "checked": 0
  }, {
    "title": "增产1－2％",
    "value": 2,
    "checked": 0
  }, {
    "title": "增产3－5％",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "要求矿石的成分要稳定，是指（ ）稳定。",
  "ans": "AB",
  "opts": [{
    "title": "ＴFe",
    "value": 0,
    "checked": 0
  }, {
    "title": "碱度",
    "value": 1,
    "checked": 0
  }, {
    "title": "SiO2",
    "value": 2,
    "checked": 0
  }, {
    "title": "Al2O3",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "烧结矿中的Al2O3主要存在于（ ）中。",
  "ans": "ABC",
  "opts": [{
    "title": "黄长石",
    "value": 0,
    "checked": 0
  }, {
    "title": "铁酸钙",
    "value": 1,
    "checked": 0
  }, {
    "title": "硅酸盐渣相",
    "value": 2,
    "checked": 0
  }, {
    "title": "硅酸钙",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "炉渣的表面性质指的是（ ）。",
  "ans": "AC",
  "opts": [{
    "title": "液态炉渣与煤气间的表面张力",
    "value": 0,
    "checked": 0
  }, {
    "title": "煤气间与铁水的表面张力",
    "value": 1,
    "checked": 0
  }, {
    "title": "渣铁间的界面张力",
    "value": 2,
    "checked": 0
  }, {
    "title": "液态炉渣与焦炭的表面张力",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "风温提高后（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "风口前燃烧碳量减",
    "value": 0,
    "checked": 0
  }, {
    "title": "风口区煤气量减少",
    "value": 1,
    "checked": 0
  }, {
    "title": "煤气和炉料的水当量比值下降",
    "value": 2,
    "checked": 0
  }, {
    "title": "炉身煤气温度下降",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "在（ ）情况下须调整焦炭负荷。",
  "ans": "ABCD",
  "opts": [{
    "title": "休风4小时以上",
    "value": 0,
    "checked": 0
  }, {
    "title": "高炉因故需采用倒装",
    "value": 1,
    "checked": 0
  }, {
    "title": "减少或停止喷吹燃料",
    "value": 2,
    "checked": 0
  }, {
    "title": "焦炭雨淋",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "高炉强化冶炼的方式有（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "精料",
    "value": 0,
    "checked": 0
  }, {
    "title": "高风温操作",
    "value": 1,
    "checked": 0
  }, {
    "title": "高压操作",
    "value": 2,
    "checked": 0
  }, {
    "title": "综合鼓风",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "煤气在料柱中运动的阻力损失随（ ）而升高。",
  "ans": "AD",
  "opts": [{
    "title": "煤气流体密度的升高",
    "value": 0,
    "checked": 0
  }, {
    "title": "形状系数增大",
    "value": 1,
    "checked": 0
  }, {
    "title": "煤气粘性系数减小",
    "value": 2,
    "checked": 0
  }, {
    "title": "煤气流经散料床层的表观平均流速增大",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "出铁出渣管理主要内容是（ ）。",
  "ans": "ABD",
  "opts": [{
    "title": "出铁速度",
    "value": 0,
    "checked": 0
  }, {
    "title": "见渣时间",
    "value": 1,
    "checked": 0
  }, {
    "title": "堵口时间",
    "value": 2,
    "checked": 0
  }, {
    "title": "铁口深度和打泥量",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "高炉长寿的技术包括（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "硬质压入技术",
    "value": 0,
    "checked": 0
  }, {
    "title": "炉缸灌浆技术",
    "value": 1,
    "checked": 0
  }, {
    "title": "钛矿护炉技术",
    "value": 2,
    "checked": 0
  }, {
    "title": "炉身上部喷涂技术",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "高炉短期控制的数学模型（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "炉热指数模型",
    "value": 0,
    "checked": 0
  }, {
    "title": "含硅量预报模型",
    "value": 1,
    "checked": 0
  }, {
    "title": "布料控制模型",
    "value": 2,
    "checked": 0
  }, {
    "title": "专家系统",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "煤中灰分主要成分是（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "SiO2",
    "value": 0,
    "checked": 0
  }, {
    "title": "Fe2O3",
    "value": 1,
    "checked": 0
  }, {
    "title": "Al2O3",
    "value": 2,
    "checked": 0
  }, {
    "title": "CaO",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "引起高炉局部管道行程的主要原因有（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "煤气流速过快",
    "value": 0,
    "checked": 0
  }, {
    "title": "炉料粒度过小",
    "value": 1,
    "checked": 0
  }, {
    "title": "炉料偏析严重",
    "value": 2,
    "checked": 0
  }, {
    "title": "炉喉及炉身内型过于凸凹不平",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "铁口数目主要取决于（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "炉容",
    "value": 0,
    "checked": 0
  }, {
    "title": "产量",
    "value": 1,
    "checked": 0
  }, {
    "title": "渣铁沟维修时间",
    "value": 2,
    "checked": 0
  }, {
    "title": "炮泥质量",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "炉渣结构理论存在两种理论学说（ ）。",
  "ans": "AC",
  "opts": [{
    "title": "分子理论",
    "value": 0,
    "checked": 0
  }, {
    "title": "原子理论",
    "value": 1,
    "checked": 0
  }, {
    "title": "离子理论",
    "value": 2,
    "checked": 0
  }, {
    "title": "质子理论",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "关于铁矿石中有害杂质的危害叙述正确的是（ ）",
  "ans": "BCD",
  "opts": [{
    "title": "Zn800℃挥发，上升后冷凝沉积于炉墙，使炉墙膨胀，破坏炉壳",
    "value": 0,
    "checked": 0
  }, {
    "title": "Pb易还原，易沉于炉底，破坏砖衬",
    "value": 1,
    "checked": 0
  }, {
    "title": "砷使钢冷脆，不易焊接",
    "value": 2,
    "checked": 0
  }, {
    "title": "钛降低钢的耐磨性",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "高炉冶炼过程中，（ ）有利于生铁的含C量升高。",
  "ans": "AB",
  "opts": [{
    "title": "炉内压力升高",
    "value": 0,
    "checked": 0
  }, {
    "title": "煤气中CO含量升高",
    "value": 1,
    "checked": 0
  }, {
    "title": "煤气中H2含量升高",
    "value": 2,
    "checked": 0
  }, {
    "title": "﹝S﹞含量升高",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "关于高炉四大操作制度的评价正确的是（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "送风制度对炉缸工作状态和高炉顺行是决定性因素",
    "value": 0,
    "checked": 0
  }, {
    "title": "造渣制度合理是热制度适宜的基础",
    "value": 1,
    "checked": 0
  }, {
    "title": "热制度的稳定是保证操作炉型规整合理的前提",
    "value": 2,
    "checked": 0
  }, {
    "title": "装料制度是高炉操作的核心技术和最重要的因素",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "炉缸热制度贯彻的两条原则是（ ）。",
  "ans": "AB",
  "opts": [{
    "title": "低燃耗",
    "value": 0,
    "checked": 0
  }, {
    "title": "稳定炉温",
    "value": 1,
    "checked": 0
  }, {
    "title": "高产",
    "value": 2,
    "checked": 0
  }, {
    "title": "高理论燃烧温度",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "高炉生产的主要原料是（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "铁矿石及其代用品",
    "value": 0,
    "checked": 0
  }, {
    "title": "锰矿石",
    "value": 1,
    "checked": 0
  }, {
    "title": "燃料",
    "value": 2,
    "checked": 0
  }, {
    "title": "熔剂",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "影响高炉寿命的因素有（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "冷却设备",
    "value": 0,
    "checked": 0
  }, {
    "title": "冷却制度",
    "value": 1,
    "checked": 0
  }, {
    "title": "护炉与补炉",
    "value": 2,
    "checked": 0
  }, {
    "title": "操作制度",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "焦炭的化学性质包括（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "反应性",
    "value": 0,
    "checked": 0
  }, {
    "title": "着火点",
    "value": 1,
    "checked": 0
  }, {
    "title": "发热量",
    "value": 2,
    "checked": 0
  }, {
    "title": "抗碱性",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "目前我国所使用的测定煤的着火温度的方法有（ ）。",
  "ans": "BC",
  "opts": [{
    "title": "测温法",
    "value": 0,
    "checked": 0
  }, {
    "title": "体积膨胀法",
    "value": 1,
    "checked": 0
  }, {
    "title": "温度实升法",
    "value": 2,
    "checked": 0
  }, {
    "title": "感触法",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "高压操作有利于（ ）。",
  "ans": "ABD",
  "opts": [{
    "title": "提高产量",
    "value": 0,
    "checked": 0
  }, {
    "title": "加风",
    "value": 1,
    "checked": 0
  }, {
    "title": "增加吹损",
    "value": 2,
    "checked": 0
  }, {
    "title": "压头损失降低",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "下列哪些元素的还原在高炉内无法控制（ ）。",
  "ans": "ACD",
  "opts": [{
    "title": "P",
    "value": 0,
    "checked": 0
  }, {
    "title": "V、Ti",
    "value": 1,
    "checked": 0
  }, {
    "title": "Ni",
    "value": 2,
    "checked": 0
  }, {
    "title": "Pb",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "高压操作的好处（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "煤气在炉内停留时间延长，有利于还原反应进行，有利于降低焦比",
    "value": 0,
    "checked": 0
  }, {
    "title": "有利于炉况稳定顺行",
    "value": 1,
    "checked": 0
  }, {
    "title": "炉尘量减少",
    "value": 2,
    "checked": 0
  }, {
    "title": "边缘气流受到抑制",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "提高焦炭质量的措施有（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "提高煤料的堆积密度",
    "value": 0,
    "checked": 0
  }, {
    "title": "风选调湿粉碎工艺",
    "value": 1,
    "checked": 0
  }, {
    "title": "煤预热工艺",
    "value": 2,
    "checked": 0
  }, {
    "title": "每加水控制工艺",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "焦炭中硫的形态包括（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "无机硫化物",
    "value": 0,
    "checked": 0
  }, {
    "title": "硫酸盐硫",
    "value": 1,
    "checked": 0
  }, {
    "title": "有机硫",
    "value": 2,
    "checked": 0
  }, {
    "title": "游离硫",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "高炉炼铁喷吹燃料分为以下几个阶段（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "制粉",
    "value": 0,
    "checked": 0
  }, {
    "title": "输粉",
    "value": 1,
    "checked": 0
  }, {
    "title": "喷吹",
    "value": 2,
    "checked": 0
  }, {
    "title": "煤气净化",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "熔化性温度低的炉渣稳定性就好。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "碱度越低，炉渣粘度越低。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "从还原的角度看，入炉矿粒度越小越好。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉冶炼过程中，铁氧化物的还原过程用煤气中的CO和H2作为还原剂的反应称为间接还原。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "烧结矿一般较天然矿具有较好的还原性。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "增加喷吹量，料速降低，减少喷吹物料速加快。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炉料粒度小于5mm时，入炉易于还原，对生产有利。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "现代技术水平所能提炼出铁，而且经济上合理的含铁岩石称为铁矿。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "含碱性脉石高的铁矿石，其品位应按扣除碱性氧化物含量后的铁量来评价。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉采用富氧鼓风、提高风温及其他加速扩散的技术措施，都会使燃烧带缩小。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炉况失常分为煤气流失常和热制度失常两类。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "炉渣脱S的化学反应式(CaO)+(FeS)=(CaS)+(FeO)。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "在高炉容积、炉缸直径相似的情况下，一般是风口数目越多，鼓风动能越高，风速越高。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉冶炼对焦炭粒度上限没有要求。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炼钢用生铁L08比L04含硅量要低。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "炉渣的脱硫作用就是渣中的CaO、MgO等碱性氧化物与生铁中的硫反应生成只溶于渣中的稳定化合物CaS、MgS等，从而减少生铁中的硫。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "随着高炉入炉料的品位升高，高炉炉渣量降低。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉内，间接还原反应主要是固定碳作还原剂与铁矿石之间的反应。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "铁矿石还原速度的快慢，主要取决于煤气流和矿石的特性。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "矿石批重小时，不论哪种情况布料都相对不均匀，小至一定程度会使边沿和中心无矿。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "富氧鼓风能够提高风口前理论燃烧温度和降低炉顶温度。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炉腰高度对高炉冶炼过程影响不太显著，设计时常用来调整炉容大小。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "在标准状态下，下列元素按与C发生还原反应开始温度由低到高排列为：P→Zn→Mn→V→Si→Ti。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉炉内操作的目的是保证上升的煤气流与下降的炉料顺利进行。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "风口理论燃烧温度是计算出来的，所有经验公式都是经过计算在高炉实践中经统计分析得出的。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炉内生铁和炉渣是利用它们密度不同而分离的。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "生铁成分中磷是有害元素，硫是有益元素。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉利用系数高表示日产铁量高。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉内的燃烧带也称氧化带。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "一般认为使高炉处于0.03Mpa以上压力下操作的高炉，叫高压操作。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "高炉料柱的形成是由布料方式、布料制度及炉料物理特性所决定的。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "靠近炉墙处煤气通过的越多，炉墙附近的温度就越低。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炉渣中Al2O3、CaO能减小炉渣粘度。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "适量的铜在钢中能增加抗腐蚀性，属于有益元素。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炉喉高度应以控制煤气流分布为宜，一般为4m左右。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炉渣比重一般是4.0t\/m3。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "焦炭粒度大，炉内料柱透气性就越好。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "冷却水的侵蚀性与PH值有关。PH值愈小，侵蚀性愈大。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "碳砖最初使用时，其表面应砌筑保护层。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "当＜570℃, Fe2O3与CO反应生成Fe应是放热反应。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "当温度大于570℃时，铁氧化物还原顺序为Fe2O3→Fe3O4→FeO→Fe。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "未燃煤粉在炉内的去向是还原、渗碳和随煤气逸出。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "喷吹燃料愈多理论燃烧温度愈高。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "全焦冶炼时，原料、风温、焦比不变，一定风量相应有一定的料速。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "直接还原反应是吸热反应，当炉内直接还原反应较高时，由于吸收大量的热量，使炉缸中心温度降低，影响正常的冶炼过程。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "[Si]在风口水平面含量最高而[S]反之。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉冶炼过程基本是铁氧化物还原过程。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "提高冶炼强度必将导致高炉焦比的升高。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "焦批不变，缩小矿批则焦炭负荷增大。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "在高炉冶炼过程中，铅、锌、砷、镍等都是有害元素，容易侵蚀炉底和造成炉衬损坏或结瘤。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "非正常情况下的炉料运行有炉料的流态化和存在“超越现象”。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铁口角度是指铁口中心线与水平线之间的夹角。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉焦比指的是冶炼1吨生铁原料带入的含硫量。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉去硫比炼钢去硫困难。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "高炉喷吹燃料是指从风口向高炉喷吹煤粉、重油、天然气等各种燃料，以大幅度提高焦比。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "Mn氧化物的还原顺序为：MnO2－Mn2O3－Mn3O4－MnO－Mn。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "炉渣熔化温度是指炉渣开始自由流动的温度。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉下部调剂是高炉调剂的核心。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "无钟炉顶布料的方式只有单环、多环、定点三种。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "菱铁矿的理论含铁量不高，只有48.2%，但仍具有较高的冶炼价值。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "料线在碰点以下时，炉料先撞击炉墙，然后反弹落下，矿石对焦炭的冲击作用增大，强度差的炉料撞碎，使布料层紊乱，气流分布失去控制。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "炉渣氧势越高，对炉渣脱硫反应越有利。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "正常料线应高于炉料与炉墙的碰撞点，在一定范围内降低料线加重边缘，提高料线疏松边缘。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "一般来说，焦炭的反应性越高，越易燃烧，因此其质量越好。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "炉料结构合理化不属精料内容。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "焦炭灰份增加1.0%，焦比升高2.0%，产量下降3.0%。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "焦炭的理化性质包括强度和反应性。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "冶炼铸造铁时，炉渣碱度应提高。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "容积相同，矮胖高炉易接受大风，且料柱相对较短，因而冶炼周期较短。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "矿石的开始软化温度越低，越易熔化，因此，高炉透气性越好。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "实际风速是鼓风动能中最活跃的因素。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉有效容积是指从炉底到炉喉上沿线之间的炉内容积。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "温度高于810℃时，CO 的还原能力比H2强。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "烧结粘结相最好的为铁酸钙粘结相。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "煤粉越细，自燃的可能性越大。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炉料的吸附水加热到100℃即可蒸发除去。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "在炉内高温区，矿石软化熔融后，焦炭是唯一以固态存在的物料。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "冶炼低硅生铁时，必须提高渣碱度，目的是保证炉缸温度。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉喷吹煤粉后，炉缸风口燃烧带不变。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "氢还原铁矿石的过程是放热反应过程。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉内碱金属的危害根源在于它们的循环和富集。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "生铁中[Si]的含量与温度有关,温度升高时对[Si]的还原有利。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "由于锰、硅都是有益元素，适当增加其含量，能提高钢的强度。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉有效容积利用系数随着炉役增长时炉容的扩大而不断提高。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "冶炼过程中对焦炭含水的变化不须调整入炉焦量。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "炉渣的界面张力过低，粘度高时，会造成铁珠“乳化”为高弥散的细滴，悬浮于渣中，出现很大的渣中带铁现象。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "喷吹煤粉后，炉内煤气流发生变化，一般是中心气流发展。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铁的氧化物与氧的亲合力大，分解压力就小。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "锰氧化物还原顺序为MnO3→Mn2O3→MnO→Mn。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "影响液泛因素：一是流量比因子，二是液泛因子。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "铁量差一般要求实际出铁量小于理论出铁量的10%为合格。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "焦炭回旋区上方的焦炭很密实。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "炉内煤气的水当量变化不大，炉料的水当量变化很大，随温度的升高而逐渐加大。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "烧结生产使用的燃料有点火燃料和烧结燃料两种。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉的有效容积的利用系数越小越好。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "烧结过程是弱还原性气氛，在碳粒周围局部属氧化性气氛。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "焦炭中固定碳含量与灰分互为消长。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉冶炼过程是一个连续的生产过程。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "在风量一定的条件下，扩大风口直径，燃烧带伸长。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "间接还原反应是一个不可逆放热反应，而直接还原还原是一个可逆吸热反应。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炉渣的粘度与流动性互为倒数。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "风口前碳的燃烧气化对炉料下降起决定性作用。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "分级入炉，筛除粉末是降低炉料孔隙度的有效措施。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "休风时间一般超过8h的称为长期休风。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "含Si高的铁水凝固时，断口呈黑灰色，称白口铁。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "烧结机大小按其有效抽风面积来表示。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "我国铁矿石呈现贫矿多、多元素共生的复合矿多的两大特点。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}];


module.exports = ltyl;