var scgl = [{
  "type": 1,
  "degree": 2,
  "title": "中性脉石的主要成分为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "Al2O3",
    "value": "A",
    "checked": 0
  }, {
    "title": "MgO",
    "value": "B",
    "checked": 0
  }, {
    "title": "SiO2",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉内脱硫主要靠（ ）。",
  "ans": "A",
  "opts": [{
    "title": "炉渣",
    "value": "A",
    "checked": 0
  }, {
    "title": "生铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "煤气",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "赤铁矿的主要化学成分是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "Fe3O4",
    "value": "A",
    "checked": 0
  }, {
    "title": "FeCO3",
    "value": "B",
    "checked": 0
  }, {
    "title": "Fe2O3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "在高炉冶炼过程中起主要作用的还原剂是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "H2",
    "value": "A",
    "checked": 0
  }, {
    "title": "CO",
    "value": "B",
    "checked": 0
  }, {
    "title": "固体碳",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "每立方米高炉容积每昼夜的产铁量称为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "利用系数",
    "value": "A",
    "checked": 0
  }, {
    "title": "冶炼强度",
    "value": "B",
    "checked": 0
  }, {
    "title": "焦比",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "熔剂在高炉冶炼中起的作用是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "作为还原剂",
    "value": "A",
    "checked": 0
  }, {
    "title": "使脉石、灰分与铁水分离",
    "value": "B",
    "checked": 0
  }, {
    "title": "起脱硫作用",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "矿石中最易还原的是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "磁铁矿",
    "value": "A",
    "checked": 0
  }, {
    "title": "赤铁矿",
    "value": "B",
    "checked": 0
  }, {
    "title": "褐铁矿",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "热风炉的热交换主要在（ ）中完成。",
  "ans": "A",
  "opts": [{
    "title": "蓄热室",
    "value": "A",
    "checked": 0
  }, {
    "title": "燃烧室",
    "value": "B",
    "checked": 0
  }, {
    "title": "惰性",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "由高炉生铁冶炼成钢水的过程是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "还原反应",
    "value": "A",
    "checked": 0
  }, {
    "title": "氧化反应",
    "value": "B",
    "checked": 0
  }, {
    "title": "中和反应",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉炉顶煤气温度越低，（ ）浓度越高，说明煤气能量用得越好。",
  "ans": "A",
  "opts": [{
    "title": "CO2",
    "value": "A",
    "checked": 0
  }, {
    "title": "CO",
    "value": "B",
    "checked": 0
  }, {
    "title": "H2",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "转炉炼钢时，萤石的主要作用是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "脱硫",
    "value": "A",
    "checked": 0
  }, {
    "title": "化渣",
    "value": "B",
    "checked": 0
  }, {
    "title": "脱磷",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "烧结矿的还原性一般来将比生矿（ ）。",
  "ans": "B",
  "opts": [{
    "title": "差不多",
    "value": "A",
    "checked": 0
  }, {
    "title": "好",
    "value": "B",
    "checked": 0
  }, {
    "title": "差",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉煤气是一种（ ）气体。",
  "ans": "B",
  "opts": [{
    "title": "有味",
    "value": "A",
    "checked": 0
  }, {
    "title": "有毒",
    "value": "B",
    "checked": 0
  }, {
    "title": "惰性",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "焦炭的灰分主要是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "酸性氧化物",
    "value": "A",
    "checked": 0
  }, {
    "title": "中性氧化物",
    "value": "B",
    "checked": 0
  }, {
    "title": "碱性氧化物",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "铁矿石中最易还原的是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "磁铁矿",
    "value": "A",
    "checked": 0
  }, {
    "title": "赤铁矿",
    "value": "B",
    "checked": 0
  }, {
    "title": "褐铁矿",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉内直接还原温度开始在（ ）℃。",
  "ans": "B",
  "opts": [{
    "title": "800~1000",
    "value": "A",
    "checked": 0
  }, {
    "title": "高于1100",
    "value": "B",
    "checked": 0
  }, {
    "title": "高于570",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉冶炼的主要产品是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "炉渣",
    "value": "A",
    "checked": 0
  }, {
    "title": "煤气",
    "value": "B",
    "checked": 0
  }, {
    "title": "铁水",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "大、中型高炉的碱度一般为（ ）。",
  "ans": "B",
  "opts": [{
    "title": "0.8",
    "value": "A",
    "checked": 0
  }, {
    "title": "1.1",
    "value": "B",
    "checked": 0
  }, {
    "title": "1.3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "我国高炉大小按（ ）来表示。",
  "ans": "B",
  "opts": [{
    "title": "高度",
    "value": "A",
    "checked": 0
  }, {
    "title": "有效容积",
    "value": "B",
    "checked": 0
  }, {
    "title": "内容积",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉使用的熔剂绝大数为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "酸性",
    "value": "A",
    "checked": 0
  }, {
    "title": "中性",
    "value": "B",
    "checked": 0
  }, {
    "title": "碱性",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "铁矿石的入炉粒度规定小于（ ）mm不能入炉。",
  "ans": "A",
  "opts": [{
    "title": "5",
    "value": "A",
    "checked": 0
  }, {
    "title": "8",
    "value": "B",
    "checked": 0
  }, {
    "title": "10",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉炼铁属于（ ）。",
  "ans": "B",
  "opts": [{
    "title": "湿法冶金",
    "value": "A",
    "checked": 0
  }, {
    "title": "火法冶金",
    "value": "B",
    "checked": 0
  }, {
    "title": "电冶金",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "焦炭的灰分越高，炉渣就越（ ）。",
  "ans": "B",
  "opts": [{
    "title": "差不多",
    "value": "A",
    "checked": 0
  }, {
    "title": "多",
    "value": "B",
    "checked": 0
  }, {
    "title": "少",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "褐铁矿的分子式是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "Fe203",
    "value": "A",
    "checked": 0
  }, {
    "title": "Fe3O4",
    "value": "B",
    "checked": 0
  }, {
    "title": "mFe2O3.nH2O",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉炼铁时，铁矿石品位每上升1%，焦比可以下降（ ）。",
  "ans": "B",
  "opts": [{
    "title": "1%",
    "value": "A",
    "checked": 0
  }, {
    "title": "2%",
    "value": "B",
    "checked": 0
  }, {
    "title": "3%",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉冶炼对矿石矿软化温度要求要（ ）一些好。",
  "ans": "A",
  "opts": [{
    "title": "高",
    "value": "A",
    "checked": 0
  }, {
    "title": "低",
    "value": "B",
    "checked": 0
  }, {
    "title": "适中",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "理论含铁量为72.4％的是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "Fe3O4",
    "value": "A",
    "checked": 0
  }, {
    "title": "FeCO3",
    "value": "B",
    "checked": 0
  }, {
    "title": "Fe2O3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉排出的煤气一般含有（ ）的炉尘。",
  "ans": "C",
  "opts": [{
    "title": "30~60g\/m3",
    "value": "A",
    "checked": 0
  }, {
    "title": "60~90g\/m3",
    "value": "B",
    "checked": 0
  }, {
    "title": "<30g\/m3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉内脱硫主要靠（ ）去除。",
  "ans": "A",
  "opts": [{
    "title": "炉渣",
    "value": "A",
    "checked": 0
  }, {
    "title": "生铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "煤气",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "在高炉操作中，调整装料制度我们称它为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "上部调节",
    "value": "A",
    "checked": 0
  }, {
    "title": "下部调节",
    "value": "B",
    "checked": 0
  }, {
    "title": "中部调节",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "为延长高炉一代寿命，炉缸一般采用（ ）。",
  "ans": "B",
  "opts": [{
    "title": "镶砖冷却壁",
    "value": "A",
    "checked": 0
  }, {
    "title": "光面冷却壁",
    "value": "B",
    "checked": 0
  }, {
    "title": "组合冷却壁",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉风口中套一般选用材质为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "铸铜",
    "value": "A",
    "checked": 0
  }, {
    "title": "铸铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "铸钢",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "为保证高炉连续性生产，料槽中一般存有可供高炉（ ）以上的原料。",
  "ans": "B",
  "opts": [{
    "title": "6小时",
    "value": "A",
    "checked": 0
  }, {
    "title": "8小时",
    "value": "B",
    "checked": 0
  }, {
    "title": "10小时",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "在温度高于570℃时，铁的氧化物的还原顺序为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "FeO→Fe2O3→Fe3O4→Fe",
    "value": "A",
    "checked": 0
  }, {
    "title": "Fe3O4→Fe2O3→FeO→Fe",
    "value": "B",
    "checked": 0
  }, {
    "title": "Fe2O3→Fe3O4→FeO→Fe",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "有利于高炉的生铁脱硫的条件正确的是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "足够的左右CaO",
    "value": "A",
    "checked": 0
  }, {
    "title": "炉渣的粘度要高",
    "value": "B",
    "checked": 0
  }, {
    "title": "温度低",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "粉矿造块目前最常用的是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "压块",
    "value": "A",
    "checked": 0
  }, {
    "title": "铁焦法",
    "value": "B",
    "checked": 0
  }, {
    "title": "烧结",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "钢与铁的区别，下列回答正确的是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "钢的含碳量比铁高",
    "value": "A",
    "checked": 0
  }, {
    "title": "钢的强度比铁高",
    "value": "B",
    "checked": 0
  }, {
    "title": "钢的耐磨性比铁好",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "焦炭的M40值得是（ ）强度。",
  "ans": "C",
  "opts": [{
    "title": "耐磨",
    "value": "A",
    "checked": 0
  }, {
    "title": "耐压",
    "value": "B",
    "checked": 0
  }, {
    "title": "抗破碎",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "在高炉冶炼过程中起到还原剂作用的物质是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "CO、CO2、H2",
    "value": "A",
    "checked": 0
  }, {
    "title": "CO、CO2",
    "value": "B",
    "checked": 0
  }, {
    "title": "CO、H2",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉冶炼可以去除的有害元素为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "S",
    "value": "A",
    "checked": 0
  }, {
    "title": "P",
    "value": "B",
    "checked": 0
  }, {
    "title": "Pb",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "初渣的形成包括（ ）。",
  "ans": "C",
  "opts": [{
    "title": "软化、滴落阶段",
    "value": "A",
    "checked": 0
  }, {
    "title": "固相反应、软化、滴落阶段",
    "value": "B",
    "checked": 0
  }, {
    "title": "固相反应、软化、熔融阶段、滴落阶段",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉炉底冷却采用（ ）。",
  "ans": "B",
  "opts": [{
    "title": "清循环水",
    "value": "A",
    "checked": 0
  }, {
    "title": "纯水",
    "value": "B",
    "checked": 0
  }, {
    "title": "工业水",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉冶炼过程中，P的去向有（ ）。",
  "ans": "C",
  "opts": [{
    "title": "大部分进入生铁",
    "value": "A",
    "checked": 0
  }, {
    "title": "一部分进入生铁，一部分进入炉渣",
    "value": "B",
    "checked": 0
  }, {
    "title": "全部进入生铁",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉中铁大约还原达到（ ）。",
  "ans": "C",
  "opts": [{
    "title": "90%",
    "value": "A",
    "checked": 0
  }, {
    "title": "95%",
    "value": "B",
    "checked": 0
  }, {
    "title": "99.5%",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉冶炼条件下，下列氧化物最易还原的是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "CaO",
    "value": "A",
    "checked": 0
  }, {
    "title": "FeO",
    "value": "B",
    "checked": 0
  }, {
    "title": "SiO2",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉内的（ ）是热量的主要传递者。",
  "ans": "A",
  "opts": [{
    "title": "煤气",
    "value": "A",
    "checked": 0
  }, {
    "title": "矿石",
    "value": "B",
    "checked": 0
  }, {
    "title": "焦炭",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉煤气和部分焦炭夺取铁矿石中的氧，这一过程称作（ ）。",
  "ans": "C",
  "opts": [{
    "title": "氧化过程",
    "value": "A",
    "checked": 0
  }, {
    "title": "物理反应",
    "value": "B",
    "checked": 0
  }, {
    "title": "还原过程",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉冶炼过程中，不能去除的有害元素是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "C",
    "value": "A",
    "checked": 0
  }, {
    "title": "P",
    "value": "B",
    "checked": 0
  }, {
    "title": "S",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "一般把实际含铁量占理论含铁量（ ）以上的矿石称为富矿。",
  "ans": "A",
  "opts": [{
    "title": "70％",
    "value": "A",
    "checked": 0
  }, {
    "title": "60％",
    "value": "B",
    "checked": 0
  }, {
    "title": "50％",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉内氧化物在逐级还原的过程中（ ）是最关键的。",
  "ans": "A",
  "opts": [{
    "title": "FeO",
    "value": "A",
    "checked": 0
  }, {
    "title": "Fe3O4",
    "value": "B",
    "checked": 0
  }, {
    "title": "Fe2O3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "铁水中硅大量被还原的区域是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "炉缸",
    "value": "A",
    "checked": 0
  }, {
    "title": "滴落带",
    "value": "B",
    "checked": 0
  }, {
    "title": "软熔带",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉煤气除尘后在保持的净煤气要求,其中含尘率为（ ）。",
  "ans": "C",
  "opts": [{
    "title": "小于30mg\/Nm3",
    "value": "A",
    "checked": 0
  }, {
    "title": "小于20mg\/Nm3",
    "value": "B",
    "checked": 0
  }, {
    "title": "小于10mg\/Nm3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉炉尘一般含铁30～50%,含碳在（ ）经除尘回收后可作烧结原料。",
  "ans": "C",
  "opts": [{
    "title": "20～30%",
    "value": "A",
    "checked": 0
  }, {
    "title": "15～25%",
    "value": "B",
    "checked": 0
  }, {
    "title": "10～20%",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉煤气中CO的含量在（ ）。",
  "ans": "A",
  "opts": [{
    "title": "20%以上",
    "value": "A",
    "checked": 0
  }, {
    "title": "30%以上",
    "value": "B",
    "checked": 0
  }, {
    "title": "10～20%",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "以下（ ）金属元素在高炉冶炼条件下是完全不被还原的。",
  "ans": "C",
  "opts": [{
    "title": "Ca、Al、Si",
    "value": "A",
    "checked": 0
  }, {
    "title": "Cr、V、Ti",
    "value": "B",
    "checked": 0
  }, {
    "title": "Al、Mg、Ca",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉内型是指高炉冶炼的空间轮廓，由炉缸、炉腹、炉腰和（ ）五部分组成。",
  "ans": "C",
  "opts": [{
    "title": "炉身及炉顶",
    "value": "A",
    "checked": 0
  }, {
    "title": "炉身及炉基",
    "value": "B",
    "checked": 0
  }, {
    "title": "炉身及炉喉",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉冶炼的副产品有（ ）。",
  "ans": "A",
  "opts": [{
    "title": "炉渣",
    "value": "A",
    "checked": 0
  }, {
    "title": "生铁",
    "value": "B",
    "checked": 0
  }, {
    "title": "返矿",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "碱度为（ ）的叫高碱度烧结矿。",
  "ans": "B",
  "opts": [{
    "title": "1.2～1.3",
    "value": "A",
    "checked": 0
  }, {
    "title": "1.5～3.5",
    "value": "B",
    "checked": 0
  }, {
    "title": "＞3.5",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "焦炭灰份含量与强度之间（ ）关系。",
  "ans": "A",
  "opts": [{
    "title": "成反比",
    "value": "A",
    "checked": 0
  }, {
    "title": "成正比",
    "value": "B",
    "checked": 0
  }, {
    "title": "无影响",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "焦炭灰份变化1.0%，影响焦比为（ ）。",
  "ans": "B",
  "opts": [{
    "title": "1.0%",
    "value": "A",
    "checked": 0
  }, {
    "title": "2.0%",
    "value": "B",
    "checked": 0
  }, {
    "title": "3.0%",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "焦炭在炉内唯一不能被煤粉代替的作用是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "还原剂",
    "value": "A",
    "checked": 0
  }, {
    "title": "渗碳剂",
    "value": "B",
    "checked": 0
  }, {
    "title": "料柱骨架",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "就金属而言，铁在自然界中的贮存量居第（ ）位。",
  "ans": "B",
  "opts": [{
    "title": "一",
    "value": "A",
    "checked": 0
  }, {
    "title": "二",
    "value": "B",
    "checked": 0
  }, {
    "title": "三",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "矿石脉石中（ ）高对高炉冶炼不利。",
  "ans": "C",
  "opts": [{
    "title": "MgO",
    "value": "A",
    "checked": 0
  }, {
    "title": "Al2O3",
    "value": "B",
    "checked": 0
  }, {
    "title": "SiO2",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "炼铁工作者通常用生铁中的含（ ）量来表示炉温。",
  "ans": "C",
  "opts": [{
    "title": "Mn",
    "value": "A",
    "checked": 0
  }, {
    "title": "S",
    "value": "B",
    "checked": 0
  }, {
    "title": "Si",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "炉缸煤气成分主要包括（ ）。",
  "ans": "A",
  "opts": [{
    "title": "CO、H2、N2",
    "value": "A",
    "checked": 0
  }, {
    "title": "CO、CO2、H2",
    "value": "B",
    "checked": 0
  }, {
    "title": "CO、CO2、N2",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "炉内低于800℃区域是（ ）还原为主。",
  "ans": "B",
  "opts": [{
    "title": "直接还原",
    "value": "A",
    "checked": 0
  }, {
    "title": "间接还原",
    "value": "B",
    "checked": 0
  }, {
    "title": "二种还原均在",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "炉渣温度比铁水温度（ ）。",
  "ans": "A",
  "opts": [{
    "title": "高50～100℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "低50～100℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "相同",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "热风炉用高炉煤气的含尘量应小于（ ）。",
  "ans": "A",
  "opts": [{
    "title": "10mg\/m3",
    "value": "A",
    "checked": 0
  }, {
    "title": "30mg\/m3",
    "value": "B",
    "checked": 0
  }, {
    "title": "20mg\/m3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "铁矿石中（ ）属于有害元素。",
  "ans": "B",
  "opts": [{
    "title": "钒",
    "value": "A",
    "checked": 0
  }, {
    "title": "硫",
    "value": "B",
    "checked": 0
  }, {
    "title": "铝",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "铁矿石中的有害元素是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "Mn",
    "value": "A",
    "checked": 0
  }, {
    "title": "P",
    "value": "B",
    "checked": 0
  }, {
    "title": "Ti",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "我国规定矿石中的有害元素硫要（ ）%。",
  "ans": "A",
  "opts": [{
    "title": "≤0.3",
    "value": "A",
    "checked": 0
  }, {
    "title": "≤0.4",
    "value": "B",
    "checked": 0
  }, {
    "title": "≤0.5",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "吸附水在炉料加热到（ ）时即激烈蒸发。",
  "ans": "B",
  "opts": [{
    "title": "80℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "100℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "110℃",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "在高炉下部高温区，焦炭以（ ）存在。",
  "ans": "A",
  "opts": [{
    "title": "固态",
    "value": "A",
    "checked": 0
  }, {
    "title": "粉末",
    "value": "B",
    "checked": 0
  }, {
    "title": "液态",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "在一般炼铁生产中，有（ ）左右的硫是由焦炭带入高炉的。",
  "ans": "C",
  "opts": [{
    "title": "60%",
    "value": "A",
    "checked": 0
  }, {
    "title": "50%",
    "value": "B",
    "checked": 0
  }, {
    "title": "80%",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "渣中（ ）增加时有利于炉渣脱硫。",
  "ans": "B",
  "opts": [{
    "title": "FeO",
    "value": "A",
    "checked": 0
  }, {
    "title": "MgO",
    "value": "B",
    "checked": 0
  }, {
    "title": "SiO2",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "我国常用的冷却设备有（ ）。",
  "ans": "C",
  "opts": [{
    "title": "冷却壁",
    "value": "A",
    "checked": 0
  }, {
    "title": "冷却板",
    "value": "B",
    "checked": 0
  }, {
    "title": "以上均是",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉内直接和间接还原共存的区间是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "570℃～800℃",
    "value": "A",
    "checked": 0
  }, {
    "title": "800～1100℃",
    "value": "B",
    "checked": 0
  }, {
    "title": "1100～1300℃",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "炉缸煤气中含量最高的成分是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "N2",
    "value": "A",
    "checked": 0
  }, {
    "title": "H2",
    "value": "B",
    "checked": 0
  }, {
    "title": "CO",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉常用的冷却介质有（ ）。",
  "ans": "C",
  "opts": [{
    "title": "水",
    "value": "A",
    "checked": 0
  }, {
    "title": "空气",
    "value": "B",
    "checked": 0
  }, {
    "title": "水、水蒸气",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "光面冷却壁用于（ ）部位。",
  "ans": "C",
  "opts": [{
    "title": "炉底",
    "value": "A",
    "checked": 0
  }, {
    "title": "炉身",
    "value": "B",
    "checked": 0
  }, {
    "title": "炉缸",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉炼铁是把矿石（ ）成生铁和炉渣。",
  "ans": "B",
  "opts": [{
    "title": "氧化",
    "value": "A",
    "checked": 0
  }, {
    "title": "还原",
    "value": "B",
    "checked": 0
  }, {
    "title": "分解",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "使用煤气时应该（ ）。",
  "ans": "A",
  "opts": [{
    "title": "先开气后点火",
    "value": "A",
    "checked": 0
  }, {
    "title": "边开气边点火",
    "value": "B",
    "checked": 0
  }, {
    "title": "先点火后开气",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "适合高炉冶炼合适的矿石粒度为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "6-25㎜",
    "value": "A",
    "checked": 0
  }, {
    "title": "6-20㎜",
    "value": "B",
    "checked": 0
  }, {
    "title": "6-40㎜",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "高炉喷煤后（ ）明显增加。",
  "ans": "A",
  "opts": [{
    "title": "H2",
    "value": "A",
    "checked": 0
  }, {
    "title": "CO",
    "value": "B",
    "checked": 0
  }, {
    "title": "CO2",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "高炉炉渣粘度越大，流动性（ ）。",
  "ans": "B",
  "opts": [{
    "title": "越好",
    "value": "A",
    "checked": 0
  }, {
    "title": "越差",
    "value": "B",
    "checked": 0
  }, {
    "title": "不变",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 2,
  "title": "目前，我国高炉以喷吹（ ）为主。",
  "ans": "A",
  "opts": [{
    "title": "煤粉",
    "value": "A",
    "checked": 0
  }, {
    "title": "天然气",
    "value": "B",
    "checked": 0
  }, {
    "title": "焦粉",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "焦炭的主要化学成分是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "C",
    "value": "A",
    "checked": 0
  }, {
    "title": "CO",
    "value": "B",
    "checked": 0
  }, {
    "title": "CO2",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "烧结矿碱度表达式正确的是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "R＝SiO2\/CaO",
    "value": "A",
    "checked": 0
  }, {
    "title": "R＝CaO\/SiO2",
    "value": "B",
    "checked": 0
  }, {
    "title": "R＝MgO\/Al2O3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "焦炭中固定碳的高低主要取决于（ ）高低。",
  "ans": "B",
  "opts": [{
    "title": "挥发分",
    "value": "A",
    "checked": 0
  }, {
    "title": "灰分",
    "value": "B",
    "checked": 0
  }, {
    "title": "水分",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉有效容积为2500m3，利用系数为2.0时，日产量是（ ）t。",
  "ans": "C",
  "opts": [{
    "title": "2750",
    "value": "A",
    "checked": 0
  }, {
    "title": "3500",
    "value": "B",
    "checked": 0
  }, {
    "title": "5000",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "石灰石的分子式是（ ）。",
  "ans": "B",
  "opts": [{
    "title": "CaO",
    "value": "A",
    "checked": 0
  }, {
    "title": "CaCO3",
    "value": "B",
    "checked": 0
  }, {
    "title": "MgCO3",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "钢铁冶金主要用（ ）。",
  "ans": "A",
  "opts": [{
    "title": "火法",
    "value": "A",
    "checked": 0
  }, {
    "title": "湿法",
    "value": "B",
    "checked": 0
  }, {
    "title": "火法和湿法兼有",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "就世界范围而言，贮藏量最多且是炼铁的主要铁矿石资源（ ）。",
  "ans": "B",
  "opts": [{
    "title": "磁铁矿",
    "value": "A",
    "checked": 0
  }, {
    "title": "赤铁矿",
    "value": "B",
    "checked": 0
  }, {
    "title": "褐铁矿",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "目前球团矿主要焙烧设备是（ ）。",
  "ans": "A",
  "opts": [{
    "title": "带式焙烧机",
    "value": "A",
    "checked": 0
  }, {
    "title": "链篦机－回转窑",
    "value": "B",
    "checked": 0
  }, {
    "title": "竖炉",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 3,
  "title": "能促进生铁中含碳量增加的元素有（ ）。",
  "ans": "A",
  "opts": [{
    "title": "Mn",
    "value": "A",
    "checked": 0
  }, {
    "title": "Si",
    "value": "B",
    "checked": 0
  }, {
    "title": "P",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "粘土砖一般砌筑在高炉（ ）。",
  "ans": "A",
  "opts": [{
    "title": "炉身上部",
    "value": "A",
    "checked": 0
  }, {
    "title": "炉身下部",
    "value": "B",
    "checked": 0
  }, {
    "title": "炉缸",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "高炉煤气可燃烧成份含量最多的是（ ）。",
  "ans": "C",
  "opts": [{
    "title": "CH4",
    "value": "A",
    "checked": 0
  }, {
    "title": "H2",
    "value": "B",
    "checked": 0
  }, {
    "title": "CO",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "风温带入高炉的热量，约占高炉热量收入的（ ）。",
  "ans": "C",
  "opts": [{
    "title": "50％",
    "value": "A",
    "checked": 0
  }, {
    "title": "70～80％",
    "value": "B",
    "checked": 0
  }, {
    "title": "20～30％",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 1,
  "degree": 1,
  "title": "耐材在高温作用下不软化的性质称为（ ）。",
  "ans": "A",
  "opts": [{
    "title": "耐火度",
    "value": "A",
    "checked": 0
  }, {
    "title": "荷重软化点",
    "value": "B",
    "checked": 0
  }, {
    "title": "热稳定性",
    "value": "C",
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "下列（ ）是焦炭在高炉炼铁生产中的主要作用。",
  "ans": "ABC",
  "opts": [{
    "title": "还原剂",
    "value": 0,
    "checked": 0
  }, {
    "title": "支撑料柱的骨架作用",
    "value": 1,
    "checked": 0
  }, {
    "title": "热量",
    "value": 2,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "在高炉冶炼过程中可作为还原剂是（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "H2",
    "value": 0,
    "checked": 0
  }, {
    "title": "CO",
    "value": 1,
    "checked": 0
  }, {
    "title": "固体碳",
    "value": 2,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "高炉冶炼的副产品是（ ）。",
  "ans": "ABD",
  "opts": [{
    "title": "炉渣",
    "value": 0,
    "checked": 0
  }, {
    "title": "煤气",
    "value": 1,
    "checked": 0
  }, {
    "title": "铁水",
    "value": 2,
    "checked": 0
  }, {
    "title": "瓦斯灰",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "铁的氧化物的间接还原的还原剂是（ ）。",
  "ans": "AB",
  "opts": [{
    "title": "H2",
    "value": 0,
    "checked": 0
  }, {
    "title": "CO",
    "value": 1,
    "checked": 0
  }, {
    "title": "固体碳",
    "value": 2,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "高炉的冷却介质主要是（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "空气",
    "value": 0,
    "checked": 0
  }, {
    "title": "汽水混合物",
    "value": 1,
    "checked": 0
  }, {
    "title": "水",
    "value": 2,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "常用的高炉除尘设备是（ ）。",
  "ans": "BCD",
  "opts": [{
    "title": "布袋除尘器",
    "value": 0,
    "checked": 0
  }, {
    "title": "重力除尘器",
    "value": 1,
    "checked": 0
  }, {
    "title": "洗涤器",
    "value": 2,
    "checked": 0
  }, {
    "title": "文氏管",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "高炉送风设备主要是（ ）。",
  "ans": "AB",
  "opts": [{
    "title": "鼓风机",
    "value": 0,
    "checked": 0
  }, {
    "title": "热风炉",
    "value": 1,
    "checked": 0
  }, {
    "title": "泥炮",
    "value": 2,
    "checked": 0
  }, {
    "title": "文氏管",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "高炉煤气的成分是（ ）。",
  "ans": "ABD",
  "opts": [{
    "title": "CO2",
    "value": 0,
    "checked": 0
  }, {
    "title": "CO",
    "value": 1,
    "checked": 0
  }, {
    "title": "O2",
    "value": 2,
    "checked": 0
  }, {
    "title": "N2",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "铜是（ ）金属。",
  "ans": "BC",
  "opts": [{
    "title": "黑色",
    "value": 0,
    "checked": 0
  }, {
    "title": "有色",
    "value": 1,
    "checked": 0
  }, {
    "title": "重",
    "value": 2,
    "checked": 0
  }, {
    "title": "稀有",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "火法冶金包括（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "干燥",
    "value": 0,
    "checked": 0
  }, {
    "title": "熔炼",
    "value": 1,
    "checked": 0
  }, {
    "title": "精炼",
    "value": 2,
    "checked": 0
  }, {
    "title": "焙烧",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "湿法冶金包括（ ）。",
  "ans": "BCD",
  "opts": [{
    "title": "干燥",
    "value": 0,
    "checked": 0
  }, {
    "title": "沉积",
    "value": 1,
    "checked": 0
  }, {
    "title": "浸出",
    "value": 2,
    "checked": 0
  }, {
    "title": "置换",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 1,
  "title": "高炉冶炼的原料是（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "铁矿石",
    "value": 0,
    "checked": 0
  }, {
    "title": "焦炭",
    "value": 1,
    "checked": 0
  }, {
    "title": "熔剂",
    "value": 2,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "多数矿石中脉石的化学成分是（ ）。",
  "ans": "BD",
  "opts": [{
    "title": "MgO",
    "value": 0,
    "checked": 0
  }, {
    "title": "SiO2",
    "value": 1,
    "checked": 0
  }, {
    "title": "CaO",
    "value": 2,
    "checked": 0
  }, {
    "title": "Al2O3",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "高炉操作有（ ）基本制度。",
  "ans": "ABCD",
  "opts": [{
    "title": "热制度",
    "value": 0,
    "checked": 0
  }, {
    "title": "造渣制度",
    "value": 1,
    "checked": 0
  }, {
    "title": "装料制度",
    "value": 2,
    "checked": 0
  }, {
    "title": "送风制度",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "正常炉况的标志是（ ）。",
  "ans": "ABD",
  "opts": [{
    "title": "炉料及煤气分布均匀",
    "value": 0,
    "checked": 0
  }, {
    "title": "炉料下降顺利",
    "value": 1,
    "checked": 0
  }, {
    "title": "炉温高",
    "value": 2,
    "checked": 0
  }, {
    "title": "高炉产量高",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "高炉节能措施（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "精料",
    "value": 0,
    "checked": 0
  }, {
    "title": "高风温",
    "value": 1,
    "checked": 0
  }, {
    "title": "高压操作",
    "value": 2,
    "checked": 0
  }, {
    "title": "低硅生铁",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "对铁矿石的要求，下列回答正确的是（ ）。",
  "ans": "BC",
  "opts": [{
    "title": "脉石要多",
    "value": 0,
    "checked": 0
  }, {
    "title": "含铁量要高",
    "value": 1,
    "checked": 0
  }, {
    "title": "要有一定的机械强度",
    "value": 2,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "干法熄焦与湿法熄焦相比（ ）。",
  "ans": "ABCD",
  "opts": [{
    "title": "节约能源降低运行成本",
    "value": 0,
    "checked": 0
  }, {
    "title": "M40指标提高3～5%",
    "value": 1,
    "checked": 0
  }, {
    "title": "M10指标降低0.3～0.8%",
    "value": 2,
    "checked": 0
  }, {
    "title": "焦炭块度趋于均匀",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 3,
  "title": "促进硅还原的措施有（ ）。",
  "ans": "BC",
  "opts": [{
    "title": "提高炉渣碱度",
    "value": 0,
    "checked": 0
  }, {
    "title": "增加炉渣中SiO2的数量",
    "value": 1,
    "checked": 0
  }, {
    "title": "提高高炉下部温度",
    "value": 2,
    "checked": 0
  }, {
    "title": "降低高炉下部温度",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 2,
  "degree": 2,
  "title": "高炉冷却的目的是（ ）。",
  "ans": "ABC",
  "opts": [{
    "title": "维持内衬保持炉型",
    "value": 0,
    "checked": 0
  }, {
    "title": "形成渣皮，代替炉衬工作",
    "value": 1,
    "checked": 0
  }, {
    "title": "保护高炉炉壳和钢结构",
    "value": 2,
    "checked": 0
  }, {
    "title": "冷却均匀",
    "value": 3,
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "混匀其目的的是使矿石成分均匀化。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "要降低焦比，节约焦炭，高炉中应尽量发展直接还原，减少间接还原。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "风量大，燃烧焦炭就多，冶炼强度也就高，所以风量越大，产量越高。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "提高风温的主要作用是使高炉增加非焦炭产生的热量代替部份焦炭。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "高压操作的目的主要是降低焦比。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "含有铁元素的矿石就是铁矿石。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "S、P都是钢中的有害元素，S的存在使钢产生“冷脆性”，P的存在使钢产生“热脆性”。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "矿石的软化性是指矿石在还原气体作用下开始软化的温度。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "熄焦的方法有干法与湿法两种，宝钢主要采用干法熄焦。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "在目前的炼焦炉的条件下，所有的煤都可以炼成合格的焦炭。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "连铸得到的是钢锭，可直接送往热轧厂。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "磁铁矿的理论含铁量最高同时又是最难还原。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铁矿石的含铁量就是指矿石的品位。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "天然矿石的脉石大多数为酸性氧化物。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "“熟料”就是指烧结矿或球团矿。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "测定焦炭的强度一般用转鼓试验来实现。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉利用系数是衡量高炉生产率的一个重要指标。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "在800℃—1100℃范围内主要进行间接还原反应。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炉渣的碱度是指炉渣中的碱性氧化物与酸性氧化物重量百分含量之比。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "高炉喷煤可以降低生铁的成本。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "铁的直接还原只能发生在高炉的下部。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "磷是难还原的元素，但在高炉条件下，一般得到全部还原。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炉料中的结晶水的分解对高炉的冶炼没有多大影响。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "低硅生铁对节约焦炭，缩短炼钢时间都有好处。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "“熟料”中的FeO的含量越高，则其还原性越好。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "一般情况下当矿石的含铁量大于70％以上时称为富矿。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "含有铁元素的岩石称为铁矿石。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉操作是指开炉和停炉操作。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉喷煤可以节约焦炭。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉冶炼用CO2作还原剂。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "蓄热式热风炉的作用是加热空气。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "混匀料堆的布料、取料应遵循“平铺直取”的原则。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "烧结矿、球团矿都是人造富矿，也称“熟料”。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉冶炼的热量来源于燃料燃烧。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉仪表设备可分为控制用和检测仪表两大类。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "在高炉生产中，往往通过测定铁水中的含硅量来判断炉缸温度的高低。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铁、锰、铬等是黑色金属。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "高炉冶炼时，边缘气流应进行严格控制。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "吹透中心，炉缸工作才会活跃。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "高炉用焦M40应大于70。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉炉渣的去硫效率一般可达80％。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "R值越高，炉渣的脱硫效率越高。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉冶炼时炉内的气氛以还原性气氛为主。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "铁矿石入炉前必须进行混匀中和以稳定化学成分。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炼铁的硫主要来自于铁矿石。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉炉况正常时风压和风量成正比。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炼铁时降低炉渣中的MgO可以提高脱硫效率。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "对钢材有害的元素主要是硫、磷、砷。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铁碳合金中，碳含量>1.7%的称为钢。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "烧结机被抽风烧结的所有台车面积之和称烧结机制有效烧结面积，它的大小就是烧结机大小的标志。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炉缸是燃料燃烧和积存渣、铁水的地方，温度最高，一般在设计上冷却材料选用镶砖冷却壁。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "R=（CaO+MgO）\/SiO2称为四元碱度。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "依靠微弱的表面能吸附在炉料表面及其孔隙中的水叫做结晶水，也称化合水。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "现代高炉炼铁除了高炉向大型化发展外，正日益趋向全面自动化。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉造渣的目的是使炉渣具有良好的流动性和脱硫能力，保证生铁合格和高炉顺行。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "料槽的作用是平衡料场来料的不均衡性。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "判断炉况的方法有通过风口、渣铁直接观察和利用仪表间接判断两种。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "以SiO2为主的脉石称为碱性脉石。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "由于炼钢脱硫是吸热反应，应采用降低炉温的方法来脱硫。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉炼铁时采用的燃料一般只用煤粉而不用重油等液体燃料。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炼铁实质上是一种还原反应，而炼钢是氧化反应。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "炼铁时产生的炉渣是一种废物，应予以填埋。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉大小按内有效容积，转炉大小按平均出钢量计。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉铁水供应方式有三种，宝钢采用混铁炉供应。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "铁合金中合金元素越高，C、P等杂质含量越低。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉冶炼过程中炉料自上而下下降，煤气流从下至上上升，二者逆流式进行相对运动。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "从高炉顺行的角度来讲：炉料与煤气间的分布应该均匀分布。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铁水温度代表了高炉的化学热。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炉渣在炉缸温度下应有良好的流动性能。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉风口前的焦炭燃烧是炉内反映的核心。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "风量变化直接影响炉缸温度，是强化冶炼最有效措施。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "热风带入炉缸的高温热量是高炉的重要热源。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "冷却壁的优点是：冷却强度大、支撑耐火砖衬、便于更换，缺点是点冷却。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "喷枪插入位置应确保煤粉流与风口不摩擦，否则易损坏风口。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉生产的特点是高温、封闭、连续。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炼铁用炉料中的硫主要来自于铁矿石。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "烧结矿的FeO越高，它的还原性就越好。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炼铁时铁水温度一般控制在1400℃左右。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉冶炼时炉内的气氛以氧化性气氛为主。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炼铁时适当增加炉渣中的MgO可以提高脱硫效率。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炼铁的热量来源是靠焦炭燃烧放出的热。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "TRT是余压回收装置，用于回收高压煤气的能量。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "综合焦比是指冶炼一吨生铁所消耗的焦碳和煤粉。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "自然界里的铁元素几乎都是以氧化物的形式存在于矿石中的。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "在高炉冶炼过程中可以去除90%以上的磷。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "生铁中[Si]的含量与温度有关，温度升高时对[Si]的还原有利。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "在高炉中的还原剂为C、CO和H2。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉的炉尘回收后可作为烧结原料，也可制作水泥。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "煤气爆炸的条件是：空气、煤气混合浓度和温度。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉炉渣主要来自于矿石的脉、熔剂和焦碳灰份。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "Si、Mn、P、S的还原均在高温区域且是直接还原。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "各种矿石还原性能由好到差顺序为烧结矿→赤铁矿→菱铁矿。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "用风量调剂炉况的作用大、效果快，可以用作长期手段。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "大型高炉一般都是矮胖型内型。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "渗碳在海绵铁状态时就开始了。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "纯铁的熔点低于生铁的熔点。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "高炉脱硫效果优于转炉。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉中可脱除部分P元素。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "在800℃-1100℃高炉温区没有直接还原。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "洗煤的目的是除去原煤中的煤矸石。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉煤气着火温度为700～800℃。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "燃烧带是高炉内唯一属于氧化气氛的区域。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "直接观测判断炉况是基于生产经验的积累，主要的直观内容用：看铁水、看熔渣、看风口、看仪表四种。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "休风时间大于4小时为长期休风。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "用CO还原铁氧化物的反应都是可逆反应。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "金属氧化物的分解压越大，说明该氧化物越不稳定。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉生铁含碳量在4%左右。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "由矿石到钢材的生产流程之一：“高炉—转炉—轧机”流程，称为“短流程”。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "风口前的温度可以代表炉缸的温度。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "风口小套主要是受到渣铁的直接接触而烧坏。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉煤气比转炉煤气容易中毒。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉生产的产品是生铁，副产品是炉渣、煤气和炉尘。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉铁矿石中理论含铁量最高的是赤铁矿。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "海绵铁是铁矿石在高炉炉身部位形成的。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "决定矿石质量的因素是它的化学成份。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "风口带是高炉热能和气体还原剂的发源地和初始煤气流起点。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "炉缸的初始煤气成份为N2、CH4、CO。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "矿石的粒度影响矿石的还原速度。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "铁矿石的还原性是指矿石被还原气体CO和H2还原的难易程度。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "铁矿石的软化性是指铁矿石软化温度和软化区间两个方面。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "下部调剂指的主要是风量、风温、湿分调剂。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "锌对高炉冶炼的主要危害是损坏砖衬和生成炉瘤。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "在高炉冶炼条件下，Al2O3比MgO更易还原。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "在炉内800℃区域中以间接还原为主。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "M40代表抗冲击强度，M10代表抗摩擦强度。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "下部调剂的效果较上部调剂快而有效。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "冶炼强度越高，产量越高。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "从炉内还原角度看，焦炭粒度越大越好。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉内焦炭是热量的主要传递者。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉内运动过程就是指在炉内的炉料和煤气两大流股运动过程。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "高炉内煤气经过三次分布。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "烧结过程可以去除80～90%的S等有害杂质。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "吸附水的蒸发会引起焦比升高。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "烧结矿与天然矿相比，成分稳定，粒度合适，透气性能好。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "含碳量大于2.5%是钢。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉利用系数愈高，说明高炉的生产率愈高。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "高炉炉内铁水和炉渣是利用它们密度不同而分离的。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "M10是表示焦炭耐磨强度的指标。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉冶炼可以去除一部分磷，矿石含磷量一般不作要求。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "提高风温是高炉冶炼降低焦比的一种重要手段。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "烧结矿的透气性和还原性都较天然矿石好。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "炉料在进入高炉后最先发生的反应是其吸附的水分蒸发。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "黏度低流动性好的炉渣有利于脱硫，形成渣皮保护炉衬。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "富氧送风是高炉强化冶炼的一种措施。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "煤是由古代动物埋藏地下经长期的生物、物化反应而成的一种矿物燃料。",
  "ans": "B",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 3,
  "title": "冶炼低硅生铁，对降低焦比、缩短炼钢时间都有好处。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 1,
  "title": "我国铁矿石呈现贫矿多、多元素共生的复合矿多的两大特点。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}, {
  "type": 3,
  "degree": 2,
  "title": "高炉全高是指从铁口中心线到炉顶钢圈之间的距离。",
  "ans": "A",
  "opts": [{
    "title": "对",
    "value": "A",
    "checked": 0
  }, {
    "title": "错",
    "value": "B",
    "checked": 0
  }]
}];

module.exports = scgl;